### ISSUE TITLE
Dovecot broken since migration to Yunohost 2.7.14

### ISSUE THREAD

**Issue by EricHemmy** [YunoHost/issues#1152]
yunohost    2.7.14.4 (now)
yunohost-admin    2.7.14 (now)
moulinette    2.7.14 (now)
ssowat    2.7.14 (now) 

juin 27 00:44:39 yunohost dovecot[3753]: master: Dovecot v2.2.27 (c0f36b0) starting up for imap, sieve (core dumps disabled)
juin 27 00:44:39 yunohost systemd[1]: Started Dovecot IMAP/POP3 email server.
juin 27 00:45:23 yunohost dovecot[3755]: imap-login: Fatal: Invalid ssl_protocols setting: Unknown protocol 'SSLv2'
juin 27 00:45:23 yunohost dovecot[3753]: master: Error: service(imap-login): command startup failed, throttling for 2 secs
juin 27 00:45:25 yunohost dovecot[3755]: imap-login: Fatal: Invalid ssl_protocols setting: Unknown protocol 'SSLv2'
juin 27 00:45:25 yunohost dovecot[3753]: master: Error: service(imap-login): command startup failed, throttling for 4 secs
juin 27 00:45:29 yunohost dovecot[3755]: imap-login: Fatal: Invalid ssl_protocols setting: Unknown protocol 'SSLv2'
juin 27 00:45:29 yunohost dovecot[3753]: master: Error: service(imap-login): command startup failed, throttling for 8 secs
juin 27 00:45:37 yunohost dovecot[3755]: imap-login: Fatal: Invalid ssl_protocols setting: Unknown protocol 'SSLv2'
juin 27 00:45:37 yunohost dovecot[3753]: master: Error: service(imap-login): command startup failed, throttling for 16 secs

Trying something, but doesn't work : unable to log in to mail server.

**Comment by alexAubin** [comment]
Uuuuh, can you comment on the fact that the version you show is still "2.7.14" and not 3 ?

**Comment by EricHemmy** [comment]
Sorry ...

**Comment by alexAubin** [comment]
So did you migrate or not ? 

Please provide some context ... A quick look at the error tells me that this is related to OpenSSL 1.1 which is on Stretch if I remember correctly. So that looks like you attempted a migration but it was not fully completed ? Did you follow the instructions on https://yunohost.org/#/jessie_stretch_migration ?

Please provide some context ... people in the project can help, but they can't magically guess context :| What have you done prior to this situation ? What are you trying to achieve ? Have you manually edited the dovecot conf in the past ?

**Comment by EricHemmy** [comment]
No ! I did a restore of my VM. Too many things broken (NextCloud + RoundCube + Shell In A Box, at least ...).
I don't know exactly what happen.
Thank you for the link about "Jessie to Stretch migration" : I'll read this page before a new jump in th future ;-)
Thanks again for your help.

**Comment by alexAubin** [comment]
Closing issue because of lack of clear context and info and because "SSLv2" is not in 3.x's conf file anymore anyway. Sorry :/
