### ISSUE TITLE
add apt-transport-https

### ISSUE THREAD

**Issue by Jibec** [YunoHost/issues#1242]
hi,

can you please restore "apt-transport-https" as a depedency of yunohost?

This package looks like to be part of the install script:

see https://github.com/YunoHost/issues/issues/1008 and https://install.yunohost.org/

But somehow, it crashes on my server for peertube: https://github.com/YunoHost-Apps/peertube_ynh/blob/0c6e247773cdc85ce1385ed6ec274aa3fb505d18/scripts/install#L98

I assume old installation don't have this package, so for some of us the package crashes, while it works fine for others

**Comment by maniackcrudelis** [comment]
If apt-transport-https is for [adding external apt repo in YunoHost](https://github.com/YunoHost-Apps/peertube_ynh/blob/master/scripts/install#L97), that sure that I'm not going to say that's a good idea...

**Comment by frju365** [comment]
Well, I know what is it... but it doesn't create any problem as far as I know and no, it just to make apt able to read repos in https://* instead of http://*.  As everyrepo (with community repos of debian) are in http://, ofc it will be used to have other official repo.

**Comment by maniackcrudelis** [comment]
I know what the purpose of this package. But adding extra repo isn't a good idea, as we can't know what is in this repo, and what's going to be upgraded from those repos.
It can, and it did many times, induce a lot of strange errors because a repo has newer versions of a package, which is not fully supported by Debian.

So, I maintain, adding a extra repo is not a good idea...
Using a deb package is better.

**Comment by frju365** [comment]
Instead of a deb, we can mark an hold on a package too : http://manpages.ubuntu.com/manpages/xenial/man8/apt-mark.8.html instead of downloading a deb and verifying it (advantage of the repos is that we are sure it comes from an official repos). Well it's two points of view... not adding this package won't prevent ppl from using http://* repos.

**Comment by maniackcrudelis** [comment]
For sure it won't avoid packagers to do so, but I don't want to incite them to do it.
And for now, looks like YunoHost doesn't need apt-transport-https to work. And since packagers shouldn't add extra repos, it seems better to not add this package.

**Comment by frju365** [comment]
ok. :-) Well I agree, i just have doubts it good idea to install it through app directly, but ok.

**Comment by maniackcrudelis** [comment]
When downloading a deb, you can download it from the official repo, and verify the checksum.
But ~maybe~ probably we should add a new helper to do that without all the process of `ynh_setup_source`

**Comment by Jibec** [comment]
Depending on how you install YunoHost, you may have this dependency or not: https://github.com/YunoHost/install_script/commit/e5677b4775e8766fae964825b7c5d7d9aaf30473

About having or not having this package by default, I can't see how to properly use up to date PHP version with Debian stretch:
See https://secure.php.net/supported-versions.php and https://packages.debian.org/stretch/php/php

What's your recommendation for packagers? Should we do something with package_check?
FYI, this package is quite widely used already: https://github.com/search?q=org%3AYunoHost-Apps+apt-transport-https&type=Code

**Comment by maniackcrudelis** [comment]
> About having or not having this package by default, I can't see how to properly use up to date PHP version with Debian stretch

Are we always going to have this discussion...? We're on Debian, which means that we're not going to have up to date packages. If that's a problem, go say that to Debian maintainers...

> What's your recommendation for packagers? Should we do something with package_check?

Like what ? I don't see the point here.

> this package is quite widely used already

Have you read the discussion above ?
https://github.com/YunoHost-Apps/mastodon_ynh/blob/master/scripts/install#L87
https://github.com/YunoHost-Apps/onlyoffice_ynh/blob/master/scripts/install#L117
https://github.com/YunoHost-Apps/grafana_ynh/blob/master/scripts/_common.sh#L40 and following
https://github.com/YunoHost-Apps/peertube_ynh/blob/master/scripts/install#L97
https://github.com/YunoHost-Apps/monica_ynh/blob/master/scripts/_common.sh#L109
https://github.com/YunoHost-Apps/Firefly-III_ynh/blob/master/scripts/_common.sh#L119
https://github.com/YunoHost-Apps/gitlab_ynh/blob/master/scripts/install#L45
https://github.com/YunoHost-Apps/pleroma_ynh/blob/master/scripts/install#L95-L100
https://github.com/YunoHost-Apps/collaboraonline_ynh/blob/master/scripts/install#L91-L96
https://github.com/YunoHost-Apps/kimai2_ynh/blob/master/scripts/_common.sh#L136
-_- ...

**Comment by Jibec** [comment]
I see a bug and a need to write down a guideline to help packagers (the linter could raise a warning or an error to make sure the packager knows what's the proper way of doing things).

According to your message, it seems to be no issue, feel free to close the issue instead of being aggressive again.

**Comment by yalh76** [comment]
apt-transport-https is not included in Yunohost ISO but is included in the install script: https://install.yunohost.org/ or https://github.com/YunoHost/install_script used by package_check

This caused an issue in a package I work for: https://github.com/YunoHost-Apps/wikijs_ynh/issues/23

- Install of the package work for me as I have a Debian installation + Yunohost https://install.yunohost.org/ installation
- Install of the package work for package_check too
- Installation of the package on a fresh install from last yunohost 3.4.2.2 iso doessn't work

Having the iso install and the web install with different dependencies is not a very good idea...
So, is it possible to:
1. Include apt-transport-https package in the iso build
or
2. Remove the dependency to apt-transport-https in the web install

As far as I understand all this, option 2 would be stupid, IT history goes to full https... and one day even default /etc/apt/sources.list will use https instead of http. Debian package repositories are already available using https...

**Comment by yalh76** [comment]
Another difference between the iso install and the web install:
in iso install 
`## YunoHost repository
deb http://forge.yunohost.org/debian/ stretch stable` is added in /etc/apt/sources.list

In web install
`deb http://forge.yunohost.org/debian/ stretch stable`
is added in /etc/apt/sources.list.d/yunohost.list

**Comment by alexAubin** [comment]
>in iso install
>`## YunoHost repository deb http://forge.yunohost.org/debian/ stretch stable` is added in /etc/apt/sources.list

Ah that's a good catch ... I'm gonna fix this, thanks

(Edit : well unfortunately it's not something trivial to fix @.@ ...)

**Comment by alexAubin** [comment]
Fixed in https://github.com/YunoHost/yunohost/pull/658
