### ISSUE TITLE
Update Metronome's package to latest stable build 3.11.8

### ISSUE THREAD

**Issue by maranda** [YunoHost/issues#1269]
It's got some important fixes/changes.

**Comment by alexAubin** [comment]
To report some discussion and stuff that happened on the chat : due to this issue (bug in yunohost) https://github.com/YunoHost/issues/issues/1232 fixed by this PR https://github.com/YunoHost/yunohost/pull/614 we froze the release of new metronome for a few weeks to try to get as many people on 3.4 before releasing new version of metronome ...

This in fact has not so much to do with metronome but about yunohost upgrade mechanism ;) Maybe there are other approaches (to be implemented directly in metronome's debian package ?) that could be found to not trigger https://github.com/YunoHost/issues/issues/1232, i dunno ...

**Comment by alexAubin** [comment]
(Note that metronome 3.11.5 is available in the `testing` repo of yunohost though, if you really need to get it :/)

**Comment by maranda** [comment]
To note that 3.11.6 will have occupant list persistence for MUC across shutdowns/restarts, but I'd wait for 3.11.7 since it has some additional bug fixes and reCAPTCHA integration in mod_spim_block.

**Comment by maranda** [comment]
And beside .7 had to rush out 3.11.8 as working on today, I found some more outstanding bugs some are pretty bad security vulnerabilities one in mod_pep and that needs to be addressed ASAP.

**Comment by alexAubin** [comment]
This is done, AFAIK we are shipping 3.12 now
