### ISSUE TITLE
ssh migration that disable root user doesn't migrate ssh authorized keys to admin user

### ISSUE THREAD

**Issue by Psycojoker** [YunoHost/issues#1285]
This breaks authentication for people that uses that, I had one case today.

**Comment by opi** [comment]
Critical bug IMHO, I'm glad to have manually migrate `/root/.ssh/*` to `/home/admin/.ssh/` before applying this migration.

**Comment by Gofannon** [comment]
I ban myself for one week thanks to fail2ban because of this.

See here for how to migrate keys as described by Opi : https://forum.yunohost.org/t/ssh-auth-via-private-public-key-impossible/7007/4

**Comment by Jaxom99** [comment]
Same issue on a newly installed server here. Ofc you may login via password in the meantime, but I think it would be a good behaviour from Yunohost...

**Comment by ketsapiwiq** [comment]
Thought a bit about this, this would mean:
- to add in the install script a warning saying that `authorizedkeys` of root is being copied to `/home/admin`
- to edit the `regenconf.py` to re-apply this change when regenerating the SSH config.

But since https://github.com/YunoHost/yunohost/pull/1408 will allow multiple admins, we'll need to rethink it.

In my opinion, we should change YunoHost's policy for the SSH `root` login:
- allow login to `root` with a public key on any interface, because **when password login is disabled** I think it's being superstitious to disable `root` login for publicly exposed IPs (e.g. VPS providers like Scaleway and Hetzner pre-seed the `root` user's `authorized_keys` file). 
- only allow login to `root` with a password when on a local interface, which is already the case. It's not my usecase at all but apparently it is for some people and the Internet Cube users

Another thing that would enhance the SSH login management in YunoHost is mentioned in this issue: https://github.com/YunoHost/issues/issues/175

**Comment by alexAubin** [comment]
This migration is super old, closing
