### ISSUE TITLE
What should we do when an app is know to be dangerous yet can have a good level ...

### ISSUE THREAD

**Issue by alexAubin** [YunoHost/issues#1318]
c.f. for instance https://forum.yunohost.org/t/nextcloud-15-et-php7-3/7297

Pilea installed Php7.3 which in turn broke other stuff ... what do we do with this. Pilea happened to be level 5 at some point, and could even have been level 7 ...

Ideally we should a mecanism or procedure to flag this kind of app as "dangerous" and discourage people from using it / warn people about the risk ... Idk

**Comment by maniackcrudelis** [comment]
> "[...] la dernière mise à jour m’a rajouté un nouveau dépot qui a des versions plus récentes de php que le standard…"

Again... Hopefully I didn't update that app yet...

Pilea is level 7... https://github.com/YunoHost/apps/blob/master/community.json#L1231
As I can read, Krakinou is going to remove this version of php, but I guess this is needed for pilea to work.
Php is a recurrent problem, which should be fixed with a helper. I can have a look to it...

Still, the problem here is about dangerous apps.
For an app like this one, neither old nor unmaintained. We can't just put the app as not working to prevent any further problems.
Maybe the better things to do would be to put it as inprogress, with an issue on the repo ?

That's actually a tricky issue... That app is quite good, the packager, which is also the upstream dev, is working hard on it. Still, this app could indeed be dangerous !

**Comment by maniackcrudelis** [comment]
About adding new repositories, I completed the helpers started by @frju365 
https://github.com/YunoHost-Apps/Experimental_helpers/blob/master/ynh_add_secure_repos/ynh_add_secure_repos__2

With `ynh_install_extra_repo`, any extra repository will have a pin of 50, which should avoid any new problems with apt.

**Comment by Psycojoker** [comment]
Should we close this issue then?

**Comment by alexAubin** [comment]
Hmmm well I would wait for until https://github.com/YunoHost/yunohost-admin/pull/242 get merged (or closed without merging :wink:) because it includes a change in the default filter, such that only "decent quality apps" (= apps at least level 5, for which the linter is happy) are listed.

In combination with the fact that the linter now reports tweaking the sources.list as an error + there are helpers to correctly handle extra repo and php versions, this kinda sort of adresses the issue for now I think ...
