### ISSUE TITLE
[ynh-dev] feedback on trying to setup local development

### ISSUE THREAD

**Issue by decentral1se** [YunoHost/issues#1353]
Today, I spent a few hours trying to get a local development of yunohost setup on Debian stretch. I failed unfortunately. I had to compile LXC from source, then struggled with the network settings and then finally ran into a very obscure error regarding some volume groups (posted to `#yunohost-dev`).

My feedback is then:

* It is not clear what version of LXC, Vagrant, Vagrant-LXC, and Virtualbox (if that is even the provider that is being used by others?) are required to make this work. What are the current developers using and know that works? Could this be documented more clearly?

* Vagrant-LXC is not being maintained now (see https://github.com/fgrehm/vagrant-lxc/issues/375) and it is being recommended to use here. It's not clear if this still works and with what versions? This is quite problematic.

* Given that the script requires LXC >= 3 and this is not available on the current LTS of Debian, new contributors must install it from source. I think that is an issue in itself.

Some proposals for improvement:

* Until issues above are mentioned, do not recommend to use LXC/Vagrant setup for local development installations for contributors.
* Only recommend to use a "remote server" setup which seems quite "easy" to do
* Start a discussion (if not already?) for a more accessible local development environment using more easily supported and usable tooling (I make no judgement LXC itself btw).

I hope this is constructive for you all! I am looking forward to discuss and contribute to making this a more convenient workflow for contributors in whatever way I can.

**Comment by alexAubin** [comment]
Thanks for the constructive feedback !

### About the LXC setup

- personally I'm using LXC 3.x (as required by the ynh-dev script). That's indeed not the version shipped in Debian Stretch ... but that's the version shipped in Debian Buster which is to become the new stable in 1~2 months (I expect). I guess that certainly could be made more explicit in the various doc :s 
- About `vagrant-lxc`, I'm surprised to see that it's kinda unmaintained ... But it's also shipped in Buster : https://packages.debian.org/buster/vagrant-lxc so at least it should still work for ~2 years (well at least for Buster users..)

### About ynh-dev as a whole 

it's clearly kind of a mess, because there are so many different use cases and constraints. I think there's at least all of these use cases to consider : 
    - developing+testing on a remote VPS (e.g. Scaleway)
    - developing+testing in a virtualbox
    - developing+testing in a LXC
    - developing in the host, testing in a LXC (shared folder between host and guest)
    - developing in the host, testing in a virtualbox (shared folder between host and guest)

And you have to consider what distributions is used by the various contributors (I guess we all mainly use Debian or Debian-derivative like Mint or Fedora ... but we could have contributors using Arch or other stuff).

I guess clearly the most accessible techno is virtualbox because it's easy to setup (no network config madness, no tricky version stuff like LXC). The main issue to solve with Virtualbox is the shared folder between host and guest - because you generally want to dev in the host rather than having to reinstall all the dev tooling (vim et al.) inside the guest. I think that's one of the main reason we use vagrant in the stack as it's supposed to simplify it and make it automatizable. But personally I ended up having several issues with it (buggy sharing, or buggy `vagrant-virtualbox` plugin as a whole)

Developing on a remote VPS is relatively cool and easy also - and sometimes required if you want to test features like certificate which require a server actually exposed on the internet. But I ended up using LXC because virtualbox was too heavy to run on my machine and I regularly work in a context were internet connectivity is random (so remote VPS ain't so nice). But clearly the initial LXC setup is madness and hard to debug.

Soooo I don't know what to do, to me it sounds like there's no "one solution fits all". Or maybe we should recommend something more simple like "just install virtualbox" (no vagrant madness) + "install the yunohost inside it" + "manually configure shared folders" and here you go (though I wouldn't be surprised that shared folder config or network have some subtile bits...). Then more advanced contribs could choose to switch to vagrant and/or LXC if they want/need to but at least newcomers would have an easy setup (with no vagrant madness) and start working asap. I dunno.

**Comment by eauchat** [comment]
My two cents in the discussion:

My experience installing ynh-dev some months ago was that it wasn't so easy, but also not so hard, the documentation given was pretty helpful even if not everything worked straight out of the box.
I managed to have a working dev environment, with the appropriate shared folders and a nicely "designed" working environment/workflow following the documentation, without knowing anything about LXC and vagrant.

So my first reaction is to really want to thank people who made up the system and the documentation, I don't know if I'd had the energy to put myself into development if I'd had to install manually, configure shared folders myself and figure out good working practices... And if I did, it'd probably had used a big part of my time and energy.

Also I'm not gonna say it's perfect, without changing anything to the vm's system, I regularly ran into some problems that I didn't understand, up to the point of not being able to have a working environment, and not taking time to solve the issue. In my experience it's not so stable.

Just I wouldn't throw away too fast all the great work and documentation that has been done. :heart:

**Comment by decentral1se** [comment]
Thanks @alexAubin and @eauchat!

> I wouldn't throw away too fast all the great work and documentation that has been done. :heart: 

I second this and good that we focus on the existing good work that is done :clap: I don't want to annoy anyone who is working hard here or aim to remove or break existing workflows.

So, given:

> here are so many different use cases and constraints.
> Soooo I don't know what to do, to me it sounds like there's no "one solution fits all"

I won't be recommending to change what is working now but perhaps be more explicit in the documentation regarding required skills, versions and expectations on which path to choose and how many different ways there are to solve this situation (this is mostly already done).

I'll get a PR cooking then :woman_cook:

**Comment by decentral1se** [comment]
OK, there it is: https://github.com/YunoHost/ynh-dev/pull/50 :rocket:
