### ISSUE TITLE
possibility to generate/send an invitation link to some to create a user account

### ISSUE THREAD

**Issue by Psycojoker** [YunoHost/issues#1366]
That could be quite a useful feature to spread yunohost but that's not really easy to do (we probably need a registration mechanism before that)

**Comment by alexAubin** [comment]
Discussing this today while working on Coin.

Random thoughts:
- since I worked on the auth mecanism of the moulinette, I now kinda know how it works. In the invitation link, we could provide a token. This (one-time-)token could be used in a special auth mecanism that would only be used for some route like /user/create-from-invitation.
- so around this we'd need to implement some view / form (in SSOwat?) that ask the user to fill this info
- and to effectively use this feature, we need to warn the admin that a working mail stack is required

This could actually be a pretty cool feature that could increase the adoption of yunohost since you could easily invite your friend using a button like "Invite a friend by email" on the webadmin in Users > Create

**Comment by Psycojoker** [comment]
On that subject found that stuff yesterday : https://github.com/YunoHost-Apps/subscribe_ynh

**Comment by decentral1se** [comment]
+1 +1 +1 +1 +1 +1

**Comment by zamentur** [comment]
See https://github.com/YunoHost/issues/issues/1677 for a implementation guide.

I close this ticket, as the other cover a more large case.
