### ISSUE TITLE
A broken backup script broke the upgrade definitely

### ISSUE THREAD

**Issue by zamentur** [YunoHost/issues#1368]
Currently (testing 3.6.1), if the backup script inside /etc/yunohost/apps/APP_ID/scripts/backup is broken, the app could not be upgraded. Indeed, even if a fix is created for the backup script, the old one will be executed.

This bug appears only with upgrade script using `ynh_backup_before_upgrade` .

Several ideas to fix this issue:

- Implement a --force option on upgrade to force upgrade even if the backup script fail
- Try to use the new backup script from the new version (could be risky)
- Execute backup script without set -eu
- Apply a generic backup script (or create it automatically)

**Comment by maniackcrudelis** [comment]
I think it was already that way before, regarding this line https://github.com/YunoHost/yunohost/blob/stretch-unstable/data/helpers.d/backup#L417

But I think indeed, in case the backup would fail, the upgrade should go forward but not remove and restore in case of failure.
So just go forward without security. As we can't fix a backup script without upgrade, it would be a problem otherwise.

**Comment by alexAubin** [comment]
Closing because this doesn't really happen that much (can't even recall when this happen last) and there's an option to skip the pre-upgrade backup
