### ISSUE TITLE
SSO url conflict

### ISSUE THREAD

**Issue by maniackcrudelis** [YunoHost/issues#1384]
Hey guys

Just found a strange error (in 3.5.2 :blush:), when [biboumi](https://github.com/YunoHost-Apps/biboumi_ynh/blob/master/scripts/install) is installed, the domain is no longer available for other apps.

I get this message:
```
Error: This url is not available or conflicts with the already installed app(s):
 * crudelis.fr/ → Biboumi XMPP->IRC Gateway (biboumi)
```

But biboumi does not use `ynh_webpath_register` or any other helper of that kind. And in fact biboumi does not use nginx.
Why then the domain is locked ?

**Comment by alexAubin** [comment]
That looks related to the fact that it's listed in `yunohost app map` and since it doesn't have a path, it defaults to `/` ...

c.f. https://github.com/YunoHost/yunohost/blob/stretch-unstable/src/yunohost/app.py#L433

I think the fix should be either : 
- in the core, stop assuming that if an app doesn't have a `path` it defaults to `/`
- in the app, add the `no_sso` setting such that it doesn't get displayed in the sso either, which makes sense since it's not a webapp ?

**Comment by maniackcrudelis** [comment]
What is the `no_sso` setting ?

**Comment by alexAubin** [comment]
c.f. https://github.com/YunoHost/issues/issues/50 and https://github.com/YunoHost/yunohost/pull/507

This is a specific setting meant for apps with no web interface so that they get hidden from the sso portal (and also this implicitly remove the concept of conflicting with it)

**Comment by maniackcrudelis** [comment]
That should fix the problem then.
I'll make a PR on this app.

**Comment by maniackcrudelis** [comment]
Using `no_sso` fixes the issue. Thanks for pointing me that solution.

**Comment by Psycojoker** [comment]
> in the core, stop assuming that if an app doesn't have a path it defaults to /

I'm pretty sure we should do that actually (and re-open this issue for that)
