### ISSUE TITLE
Automatically provide VPN to solve router issue

### ISSUE THREAD

**Issue by zamentur** [YunoHost/issues#1410]
As discuss, with xyz, could be useful to be able to subscribe a VPN directly from webadmin, and activate it.

Note: there is a lot of difficulties to do that (ipv4 are rare now), but could be very interesting. I suggest to have a model with several providers to avoid centralization.

**Comment by Psycojoker** [comment]
Integrating vpns (openvpn/wireguard) is something that we would be interested to have in the core since years yes, I know several people have expressed their desire to do that but no one has even actually produce the actual work yet.

**Comment by alexAubin** [comment]
Closing because it's been 5 years, cool on paper but imho the starting point is "what provider do we know that provides ethical VPNs with an API to provision them" and "how do you actually pay for this in terms of UI/UX flow" ...

Until then, imho we should instead focus on polishing vpnclient and work on allowing people to build their own VPNs, cf the (open)vpnserver app, wireguard, headscale/tailscale, SNI-based forwarding...
