### ISSUE TITLE
The website is outdated and doesn't properly explain what Yunohost does and why people could be interested

### ISSUE THREAD

**Issue by alexAubin** [YunoHost/issues#1445]
c.f. UX tests on the website during last's Brique Camp

@e-lie started a draft to redesign the website

**Comment by Bugsbane** [comment]
I know almost nothing about code, but I have experience with copywriting and marketing (ie communicating clear benefits, not the evil "trying to make people believe hype" FOSS people often assume).

There's actually a lot that is good on the Yunohost homepage already, however... the first fold of the homepage is the most important part of the whole website, and it's.... uh... not good.

The first fold is the part that decides if a new visitor will stay and learn more or bounce and go elsewhere in the first 5 seconds. It needs to communicate what Yunohost uniquely offers and to who. If you can do that, you can get people to stay and learn (ie read or watch a video) which is how you get them to give it a try which is what leads to contributors. Currently though, that whole first fold is filled with something along the lines of "Get off my cloud. WHAT?" This communicates almost nothing and doesn't even come across as friendly. I'd be prepared to bet the bounce rate of the site is horrible, if you have any analytics on it.

Anyway, I can offer help with (English) copywriting and visual design for a homepage mockup. Sadly however, my HTML/CSS skills are awful, so someone else would need to handle the code side to turn it into something useful.

**Comment by alexAubin** [comment]
Cheers, thanks for the feedback ! It would really be great if we could indeed achieve to have a fresh landing page experience, that landpage basically hasnt changed in 6~7 years.

Personally I don't know what to think about the first fold : imho it's not "horrible", but definitely not great. However I discussed with some people not necessarily geeky which thought it was good~okay

Anyway, if you have something in mind, feel free to propose a draft/mockup ! We do have ~plenty of people with HTML/CSS/JS skill around to implement a mockup if it's found to be convincing :P

**Comment by Bugsbane** [comment]
<TL/DR> What's the main short term goal of the project, who are we trying to reach and what would we be helping them to do? Then I can help get the info that would lead to a more successful homepage.</>


By the way, when I said "horrible" I was *only* talking about what I'm guessing the bounce rate is, not the quality of the home page overall. There's actually quite a lot that's good on the home page, especially some of the text like "Setup your server with ease, you already have everything at home". The problem is that the good stuff is all lower down on the page where visitors won't see it unless they scroll down. Meanwhile they're given very little reason to scroll, unless they know the project already. Some of the phrases on the first fold are also better than others (eg "Go host yourself" communicates more of Yunohosts benefit than "Get off my cloud").

Anyway, I'm happy to do mockups. The main challenge I've found with situations like this in the past, is that unless the people signing off on changes have an understanding of marketing principals, the reaction to designs tends to be based more on aesthetics than results. You have the first fold you have because someone thought it was a good idea. 'm guessing that since it was created that no one ever tried alternatives and checked the different results. Personally, from my experience I'd be prepared to bet that if you did nothing but delete that first black fold and move everything else up, you would get much, much better results all around. I might be wrong though, and only testing can say for sure. A good marketer comes up with theories to try and implements them. A great marketer tests theories and matches the results to the goals of the project. My concern is that just creating a mockup and asking "Hey, what does everyone think?" will get a lot of feedback that expresses peoples aesthetic preferences, rather than aligning the homepage with improving results towards Yunohost's defined goals.

Normally, a home page is one tool that needs to fit into an overall plan for the project. For example, if the goal is to get more people self hosting, then first comes identifying who would be the people who *aren't* self hosting, that you could help the most easily (non-hosting privacy+Linux geeks?). Then it's about figuring out where to reach them (Linux sites/podcasts/channels?) Then it's about figuring out what aspect of Yunohost appeals to them the most (fun weekend project? Help get their family off centralized services?) Then it's about tailoring the homepage to what they're looking for in the most clear and concise manner, and giving them a first easy step forwards. In this example it could be reassurance that with nothing more than a Raspberry Pi and a home router, they can get a website going, even if they've never self hosted before. Finally you give them an easy first step and how to get support, eg how to download and setting up Yunohost followed by direction to support (step by step tutorial, forum, social channels).

Maybe the immediate goal is something else though? If the goal was to get more contributors then the first question is who can you most easily reach that have the relevant skills (Python devs? CS students? Webdevs?) and motivation (privacy activists? ). After that is what Yunohost can best offer them (a way to get mentored while working on a worldwide project? A way to sharpen skills? An opportunity to fight back against GAFAM?) Then once again it's about tailoring the homepage to offer succinctly, what they're looking for, for example, maybe how to find a good beginner issue and mentoring to get their first patch merged.

Usually when people without a marketing background hear this their reaction is something along the lines of "We want everything! Can't we target everyone?" The trouble is that results come from being specific. If you offer two stories, they won't get 50% of the potential results each. They get more like 20% each and you lose 60%. That's just for two options. It gets exponentially worse, the more groups you try to reach. When what people want is buried under stuff they don't want, they go elsewhere, even if what they wanted was still there all along... For example say, a great introduction hidden underneath an obscure first fold of a website. ;)

Anyway, I tell you all of this to try and help explain why something that seems as simple as "just creating a mockup" needs to be based on a deeper understanding of the projects goals, who we're trying to reach and what we're offering them. When everyone involved understands those, there tends to be more alignment over whether a homepage mockup is likely to be effective or not (which can then be tested), instead of just whether it looks pretty (which is entirely subjective).

Personally I would suggest:

1. Setting a goal of getting a specific number of people who've never hosted before to start. This needs a metric which is tricky (Downloads? Variety of IP addresses downloading? Active noho.st users? An opt-in option to send Yunohost a victory ping, when the first app is installed?).
2. I suggest going for people who are into Linux (already technical) and privacy (motivated to get off GAFAM) who aren't hosting yet. As Yunohost becomes easier for less technical people, the goals and homepage could be adjusted, especially if we got some data about people's level of tech skills and their success rate of setting up Yunohost. After, these non-hosting people can be surveyed for what they want most (stick up a Wordpress blog? Start a Matrix server to get off Skype?) and why (protect their family? strike back against big tech?). This could be done by sticking up a survey online and asking platforms popular with this demographic to share it (eg Linux Action News, OMG Ubuntu, surveillance report podcast).
3. When we have the who (which people), the what (what they want Yunohost for) and the why (why they want to do this) then we can effectively build the how (the homepage).

I understand that what I'm talking about is a bigger project than just "have a contributor make a homepage mockup" and I'm sure all the major contributors are already busy building Yunohost. I'm not suggesting that you need to do all this. I'm happy to help and do a lot of the work. I don't speak for your project or it's goals though. If you want to let me know what the first goal is though, we can talk about how to measure it and I can take the first steps to help get there.

**Comment by xplosionmind** [comment]
Hi! I would love to help with this! Do you know where could I start?  
Where is @e-lie’s draft mentioned at the beginning?  
Any thoughts on using a SSG such as Eleventy?

**Comment by alexAubin** [comment]
Hi there,

it's in https://github.com/e-lie/yuno-landpage-grav/

Specifically in https://github.com/e-lie/yuno-landpage-grav/tree/master/pages/01.homepage/01._hero I think, but it's hard to see the actual rendering and we don't really have the screenshot of what it looked like ...

I don't know exactly where we stand about all this, naively my intuition is still that we could probably rework or improve the landpage, ideally maybe have something that would be appealing for not-so-technical people and less "geeky", i dunno

And also more understandable by not-so-technical people, like for example make it clear that YunoHost is not something you "buy online" but is something that you install on a server (and maybe have some illustration on what is a server). Also during the UX tests at the time, it was not clear for some folks what we meant by "application" ... somebody naively started to search "Facebook" and "Youtube" in the app catalog (which nowadays would list some alternatives - at the time we did not have the 'Potential alternative to' thing)

Anyway that's just random thoughts

**Comment by xplosionmind** [comment]
Thanks a lot, @alexAubin! Could I start experimenting something by using the tools I prefer?

**Comment by alexAubin** [comment]
Yes sure, regarding the tooling, I guess the discussion is less about what tool is used to create the landpage, and more about what message/"feeling" we want to communicate

**Comment by Bugsbane** [comment]
Re: The words and feelings we want to communicate:

Generally the message should be about where Yunohost stands out in dealing with the biggest problem that your potential users would have.

I'm guessing (correct me where I'm incorrect on all of this), that the primary userbase here is people who are pretty technical looking to protect the privacy and sovereignty of their families from the more harmful sides of big tech, but the complexity and perceived time requirements of rolling the whole system themselves and keeping it maintained have put them off self hosting thus far. Some may have already tried but found it too difficult / time consuming.

Where Yunohost stands out in my opinion, is:

1. You're not just swapping one company (eg Google) for another (eg Microsoft). You're swapping the profit motive for a community looking after it's own. It's entirely FOSS with no need to pay to install apps (*cough* Cloudron).
2. Simplicity. Sure anyone can technically set up a lamp stack and set up all of the apps and services themselves from scratch, but it's not going to be anywhere near as fast and easy as running the Yunohost script and following the web administration.
3. The range of apps. There are other systems to set up self hosting, but many of them only have the choice of 5-10 apps. Yunohost has how many?
4. Active development by the largest community of it's kind.

These aren't definitive, guaranteed correct answers though. The above is just my educated guesses based on my own previous experiences. Ultimately though, your community knows themselves best. I'd poll them on all of this (forum, socials etc). Eg:

1. When you first came across Yunohost, what were you hoping it would do for you?
2. Why did you want that?
3. What were the problems / difficulties standing in your way?
5. What were the other options you considered and why did you end up choosing Yunohost?
6. When you started using Yunohost, what features surprised you and what do you love the most about it now?

When you have enough answers to these questions, you'll know what draws people to using Yunohost, and the words/images to communicate that quickly and clearly are relatively simple (often the exact same wording they use!).

This is also the part that people in general almost universally want to skip. They almost always want to  jump in to writing without knowing what exactly they need to write to be effective. This is a trap. It ends up with wasting time painstakingly crafting words and images that perfectly communicate problems and benefits that potential users don't really care about.

No effective communicator can speak for a community without consulting the whole community.

<TL/DR>

Anyway, sorry for the long rant about this. As you can tell, helping FOSS communities communicate/market themselves more effectively is something I'm passionate about! ;)

The short call to action here would be to start asking some of those questions on the forums and socials, and start collecting the answers that you get in one place.

I wouldn't try doing it as a link to a survey. You'll get far more engagement if you give people short, quick questions where they can be part of a conversation than if you ask them to take an unknown amount of time to write hidden answers to questions they can't see yet without seeing any of the responses of anyone else.

**Comment by xplosionmind** [comment]
Hi! I finally managed to find some time to dedicate to this task, so that it can be addressed properly.

[I wrote a post on the forum](https://forum.yunohost.org/t/collective-rethinking-of-yunohost-landing-page-yunohost-org-refactor/29780) about this. You are most welcome to participate in the conversation/meaning!

**Comment by alexAubin** [comment]
(New website released)
