### ISSUE TITLE
The existence of the forum and chat should be made more explicit

### ISSUE THREAD

**Issue by alexAubin** [YunoHost/issues#1450]
The other day I noticed someone saying that they had an issue but "weren't aware of the existence of the forum at that time". And indeed it's not really well advertised on the current website, despite being an important source of help for newcomers ?

**Comment by eauchat** [comment]
I was looking at the website, and there is indeed lots of little and bigger things that could be done to improve it. But in the meantime, a good start for this specific issue could be to simply replace in the first screen of the homepage "Latest news" with "Forum" and make it redirect to the forum's root, no? "Latest new" leads anyway to the forum, and the announces category is in big and bold in the top of the forum's homepage, so it's hard to miss it if that's what you're looking for.
Or if some people think it's good to keep "Latest news", maybe add one more link?

That being said, maybe it's even better not to write "Forum", but "Help" and to link to the help page. But saying this I realize that there is a big "Need help ?" button in all pages of the website that is exactly doing this. But somehow I managed to miss it ;)

Maybe the best would be to revamp slightly the help page to make it a bit clearer (that said I don't find it so bad), just wondering a few things:
 - why is the homepage's "Forum and chat" purple button (in english) redirecting to the french help page? (I still don't really know how the various translated versions of pages are handled, but I'll try to understand how it works to see if I can make myself useful on that kind of stuff)
 - do we want to prioritize chat support or the forum?
 - do we want IRC to be the obvious and direct way to use the chat, or to present IRC, XMPP and Matrix equally (because now the two latter are more like footnotes).

**Comment by frju365** [comment]
I had some ideas to solve this issue : 
1/ I thought about a little fixed button at the bottom right which open perhaps the help doc in a popup.
2/ Same with the button but when we click, which displays the different main link : forum and chat.

I can begin something or we could discuss about a solution.

**Comment by alexAubin** [comment]
@frju365 : it's less about the behavior of the button than about "how to make the very existence of the forum / chat more noticeable somehow"

Still @eauchat 's remark is pretty symptomatic : 
>That being said, maybe it's even better not to write "Forum", but "Help" and to link to the help page. But saying this I realize that there is a big "Need help ?" button in all pages of the website that is exactly doing this. But somehow I managed to miss it ;)

Maybe the recent iterations on the landing page (slightly less content which should make the bottom part maybe more visible) + the webadmin (new footer in 3.7 which includes a "Need help" link) are enough to assume this is fixed, idk...

**Comment by frju365** [comment]
>@frju365 : it's less about the behavior of the button than about "how to make the very existence of the forum / chat more noticeable somehow"

Yes, but the dimension bottom-fixed like some live-chat on some e-commerce website participate, I think, to it. I was not speaking of the button's behaviors.

**Comment by alexAubin** [comment]
So meh let's say it's fixed now, since I opened the issue we have a link to the help page in the footer + now that we're on grav there's a 'Forum' link in the sidebar
