### ISSUE TITLE
Searching for "Alternative to <popular centralized service>" : design and implement a filter in the webadmin app catalog and the doc app catalog

### ISSUE THREAD

**Issue by alexAubin** [YunoHost/issues#1452]
c.f. some UX feedback in the brique camp, people don't know about Nextcloud or Rainloop or Mastodon or whatever. We should have a mechanism so that people can look for "alternatives to" stuff known from the general public like Gmail or Google Drive or Google Docs or Youtube or Whatsapp.

Secondly : even after installing apps, it would be nice if we can design a strategy such that the tile in the SSO just say e.g. "Files" for Nextcloud or "Mail" for Rainloop or "Docs" for Collabora instead of assuming that all users (not just the instance admin) will learn all app names.

**Comment by tootbrute** [comment]
Sounds like a good idea, as long as it can be configured on the user level (app names or functional names).

https://alternativeto.net/software/adobe-photoshop/ is an example of a website that sort of does what Alex is discussing.

Maybe app packagers could add a tag for a field to what their app is equivalent for.

It would be awesome if apps could be grouped by function in the App installer UX.

**Comment by Bugsbane** [comment]
You just have to be careful telling people that X is an alternative to Y, eg if you tell people that Matrix is an Alternative to WhatsApp, and they go to the effort of getting it working and then get frustrated because it won't connect to their friends on WhatsApp (out of the box, without a bridge).

Any time you tell people something is an alternative, they need to know what the differences are, which is difficult to do in the confines of an install screen. Maybe having something on the app info saying something like "Can fulfill *some* of the functions of: {Gmail/WhatsApp/Twitter/whatever...}"

**Comment by ketsapiwiq** [comment]
Here's a WIP on trying to match YunoHost apps to commercial ones, using [a scraped version](https://github.com/ketsapiwiq/ynh-scripts/blob/3d147793198fc7d2aef73084f5dd26c4c2ffaa9e/new_frama.csv) of the [Framasoft alternatives page](https://framalibre.org/alternatives):
- [github.com/ketsapiwiq/ynh-scripts/ynh-frama.csv](https://github.com/ketsapiwiq/ynh-scripts/blob/main/ynh-frama.csv)

**Comment by ketsapiwiq** [comment]
Cleaned up the list and patched catalog: https://github.com/YunoHost/apps/pull/1488

**Comment by alexAubin** [comment]
Holy shit this is merged  :star_struck: 

I'll rework the issue title to highlight the fact that it should now be integrated in the webadmin and apps catalog in the doc

**Comment by alexAubin** [comment]
Closing because it's done in the new app catalog
