### ISSUE TITLE
logging: line 90: args_array: readonly variable

### ISSUE THREAD

**Issue by alexAubin** [YunoHost/issues#1480]
Regularly seeing this kind of message upon app script failures : 

```
2019-11-04 16:00:16,220: DEBUG - + ynh_print_err ‘–message=!!\n dokuwiki’’‘s script has encountered an error. Its execution was cancelled.\n!!’
2019-11-04 16:00:16,220: WARNING - /usr/share/yunohost/helpers.d/logging: line 90: args_array: readonly variable
```

Not sure why this happens ... but would be nice to get rid of it if we can ?

**Comment by alexAubin** [comment]
ping @maniackcrudelis ... it's really not urgent, but in case you happen to have some sudden illumination about the root cause of this, could be nice to fix :sweat_smile:

**Comment by maniackcrudelis** [comment]
Do you have a larger log, to have a bit of context ?

**Comment by maniackcrudelis** [comment]
Forget the log, I just reproduced with the line 11 while working on the dedicated php services.
I'm going to investigate this...

**Comment by maniackcrudelis** [comment]
Hum... The real question is why only in such situation...
It appears that `args_array` isn't declared as a local variable, which implies that each time we call a helper inside another helper the same variable `args_array` is reused again.

To not have that variable as local is not a big problem, as the content of the array is used almost immediately by ynh_handle_getopts_args.
But, as we declare the variable as read only `-r` (Can't find the reason why... I used `-r` since the beginning with no specific explanation about it...), when a helper is called and try to write into the same variable, it failed.

My guess is, as we usually call another helper into a helper, the variable is created into another function. Which is a sub scope of the variable that has called.
But, in case of failure of an app, we're in a different situation, since `ynh_exit_properly` replace the current function, in the same scope. Here, we have a clear conflict, and here, `ynh_die` is called and try to write in `args_array`.

Anyway, the best course of action is probably to, first declare `args_array` as local, no need to be otherwise and not read only, as anyway we always call `ynh_handle_getopts_args` after the declaration of `args_array`.
I plan to do a clean of all helpers, for different small syntax residues after the merge of php helpers (no need to it twice...). I'll do that modif into that clean.

**Comment by alexAubin** [comment]
Fixed by https://github.com/YunoHost/yunohost/pull/947
