### ISSUE TITLE
YunoHost behind a proxy fails with SSL_ERROR_RX_RECORD_TOO_LONG

### ISSUE THREAD

**Issue by rissson** [YunoHost/issues#1498]
When putting a yunohost instance behind a load balancer like `haproxy`, connection is no longer possible and gets denied with an `SSL_ERROR_RX_RECORD_TOO_LONG`.
Errors can also appear this way https://stackoverflow.com/questions/59205163/haproxy-giving-pr-end-of-file-error-in-tcp-mode

A simple fix is to get nginx to accept the proxy protocol https://docs.nginx.com/nginx/admin-guide/load-balancer/using-proxy-protocol/

Is there a way we can integrate this in the generation of the configuration in YunoHost? It would not be enabled by default of course, but a way to generate all configuration with this would be nice.

**Comment by southerntofu** [comment]
Hey, could you maybe share your HAProxy setup? Your diagnosis may be correct but i don't understand why a misconfigured origin IP header would cause TLS errors.

Yunohost is intended to terminate the TLS connections on its nginx server. This means in order to proxy HTTPS your load-balancer (nginx/haproxy) needs to rely on the SNI header. On nginx, this is done matching on [ssl_preread_server_name](https://nginx.org/en/docs/stream/ngx_stream_ssl_preread_module.html) in a stream context.

**Comment by rissson** [comment]
I've moved on from this setup so I can't help you with that. I'll also close this issue because I'm probably the only one crazy enough to do this instead of simply firing up a VM
