### ISSUE TITLE
[yunohost-admin] css not compiled when building on debian buster 

### ISSUE THREAD

**Issue by arthurlutz** [YunoHost/issues#1504]
```
npm run build
npm WARN npm npm does not support Node.js v10.15.2
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/

> yunohost-admin@ build /ynh-build/yunohost-admin/src
> gulp build

[11:15:08] Using gulpfile /ynh-build/yunohost-admin/src/gulpfile.js
[11:15:08] Starting 'css'...
[11:15:08] Starting 'fonts'...
[11:15:08] Starting 'js'...
[11:15:08] Starting 'img'...
[11:15:08] Finished 'fonts' after 122 ms
Potentially unhandled rejection [2] '../bower_components/bootstrap/less/bootstrap.less' wasn't found. Tried - /ynh-build/yunohost-admin/src/bower_components/bootstrap/less/bootstrap.less,../bower_components/bootstrap/less/bootstrap.less in file /ynh-build/yunohost-admin/src/css/style.less line no. 6
[11:15:12] gulp-imagemin: Minified 5 images (saved 8.96 kB - 18.7%)
[11:15:12] Finished 'img' after 4.33 s
[11:15:13] Finished 'js' after 4.93 s
```

This is related to #1255 and trying to install yunohost on buster. 

I'm trying with vanilla debian nodejs : 

```
nodejs --version
v10.15.2
```

Should I downgrade or upgrade nodejs ?

**Comment by southerntofu** [comment]
People on [this thread](https://github.com/nodejs/help/issues/1877) suggest upgrading npm from itself: `npm install npm@latest -g`

Could you confirm whether this works for you?

EDIT: i don't think the issue is related to the node version. It seems some bootstrap stuff is not found. Am i wrong to think this could be because the postinstall script in package.json (which starts bower) is run after the build script so the dependencies are missing? Maybe #1462 will help here.

Does running `bower install` before gulp help in any way?

**Comment by alexAubin** [comment]
(This got fixed at some point, at least I havent seen this issue recently )
