### ISSUE TITLE
Make (un)protected_url/regex works again

### ISSUE THREAD

**Issue by kay0u** [YunoHost/issues#1507]
TODO:
- [x] Fix protected_uris / protected_regex not working anymore
- [ ] User with no main permission are not able to answer to link send that are unprotected

Here are old and new ssowat conf file.

stable:
> yunohost: 
  repo: stable
  version: 3.6.5.3
yunohost-admin: 
  repo: stable
  version: 3.6.5.1
moulinette: 
  repo: stable
  version: 3.6.4.1
ssowat: 
  repo: stable
  version: 3.6.4

[/etc/ssowat/conf.json](https://paste.yunohost.org/tuqaquyoxa.json)
```json
{
[...]
    "protected_regex": [
        "stable%.tld/bozon/index%.php$", 
        "stable%.tld/bozon/index%.php%?p=.*$"
    ], 
    "protected_urls": [
        "stable.tld/dotclear2/admin"
    ], 
[...]
    "unprotected_regex": [], 
    "unprotected_urls": [
        "stable.tld/bozon", 
        "stable.tld/dotclear2"
    ], 
    "users": {
        "kayou": {
            "stable.tld/bozon": "BoZoN", 
            "stable.tld/dotclear2": "DotClear 2"
        }
    }
}
```

unstable:
> yunohost: 
  repo: local
  version: 3.7.0.4+202001031317
yunohost-admin: 
  repo: local
  version: 3.7.0.1+202001031053
moulinette: 
  repo: local
  version: 3.7.0+202001031317
ssowat: 
  repo: local
  version: 3.7.0.1+202001031317

[/etc/ssowat/conf.json](https://paste.yunohost.org/gowokafahi.json)
```json
{
[...]
    "permissions": {
        "/": [
            "kayou"
        ]
    }, 
[...]
    "protected_regex": [
        "domain%.tld/bozon/index%.php$", 
        "domain%.tld/bozon/index%.php%?p=.*$"
    ], 
    "protected_urls": [
        "domain.tld/dotclear2/admin"
    ],
[...]
    "unprotected_regex": [], 
    "unprotected_urls": [
        "domain.tld/bozon", 
        "domain.tld/dotclear2"
    ], 
    "users": {
        "kayou": {
            "domain.tld/bozon": "BoZoN", 
            "domain.tld/dotclear2": "DotClear 2"
        }
    }
}
```

In both case I have `bozon` and `dotclear2` installed.

For bozon:
- 3.6 `protected_regex` makes index.php unreachable for visitors, but kayou can access it.
- 3.7 we can't access the app since no permission allow the user kayou to access to the `protected_regex` `domain%.tld/bozon/index%.php$`

For dotclear2:
- The root is accessible for visitors and kayou
- 3.6 the admin part is accessible only by kayou
- 3.7 the admin part is not accessible by kayou since no permission allow him to access to the part.

To avoid regression between 3.6 and 3.7, we should access bozon and admin part of dotclear2 if we are logged in. A logged in user should not have access to a path only if the related permission exists and if he's not in.

For the conf file, imo, the permission entry should have the absolute path:
```json
"permissions": {
        "/": [
            "kayou"
        ]
    }
```
should be:

```json
"permissions": {
        "domain.tld/app_path/": [
            "kayou"
        ]
    }
```

Well I need your help to clarify the situation and to help me to smash this bug!

**Comment by zamentur** [comment]
After reading the current code of unstable (ssowat), the permissions key in conf.json is not used by ssowat. And i think it's by design.

This key has been set for future needs. Currently it uses the user keys to know what to do.

And you are right with the fix https://github.com/YunoHost/yunohost/pull/871 Seems legit.

**Comment by zamentur** [comment]
I mean, Aleks estimate too complicated to **automatically** transform all public/private rules into permissions. It seems we need to do that app by app and migrated with upgrade script.

But you are right there is an issue with bozon and dotclear2. Aleks speak about it on forum:

> As far as I remember, the only not-backward compatible thing is the use of protected uris, in the sense that even when being logged-in you still won’t have access to the protected uris (so that’s kinda conservative). The affected apps are apparently : lstu, lufi, dotclear, lektor, bozon, and lutim.

https://forum.yunohost.org/t/yunohost-3-7-spooky-testing-call-for-feedback/9385/34?u=ljf

I remember we discuss this with aleks, probably with some aspirin tube!

So I think for this app the idea was **to create an upgrade to integrate quickly the permission system in those apps**... We had searched in all yunohost-apps for apps using protected_uris/protected_regex on another thing than /

About Maniack issue about lutim, it's due to a change in the order of protected/skipped management. In 3.6 skipped is managed after protected, in 3.7 "skipped" is managed after (see access.lua to be convinced by that).

The question is: is it normal to have a subpath protected if a path is skipped? I think no, i think this app should use unprotected instruction. 
There is one usecase with mastodon, where we are iobliged to use skipped_uris due to a bug of mastodon. We should check it would be still ok.

So i searched for origin of this not-backward compatibility describe by Aleks and i found it in migration process:
https://github.com/YunoHost/yunohost/blob/stretch-unstable/src/yunohost/data_migrations/0011_setup_group_permission.py#L121

We see clearly in this migration, that we delete the allowed_user property after filling the main permission. However in all these apps, `allowed_user` is not used for the automatically created main permission...

So if you want to fix this, we should change this migration.

I suggest to do that if we want to manage the use case of these apps:

- [ ] Modify permission 11 to detect unprotected on "/" (or skipped) and protected on subpath. In this case we need to create a second permission and `allowed_user` should be affected to it
- [ ] Modify the app_addaccess function to manage this use case too

**Comment by alexAubin** [comment]
To try to clarify a few things : 

- a ljf mentions, yes, this backward incompatibility was expected to happen after https://github.com/YunoHost/SSOwat/pull/149 and I'm not sure that there is a way to adapt the code to get rid of these incompatibility (without creating other backward incompatibilities, c.f. the original issue with ttrss). This just goes down to the fact that the legacy skipped/unprotected/protected scheme was a mess with too many different practices (e.g. apps sometimes using skipped instead of unprotected) and too many implicit/weird behaviors that we just got used to (e.g. the fact that you can protect a sub-path of a skipped url). I think naively the long-term goal should be to entirely get rid of the use of those skipped/protected/unprotected settings.

- for dotclear2 and similar apps, the real fix imho is that the app should be updated to have a second permission corresponding to the admin panel of the app - which is precisely one of the initial motivation of the permission system. (This is similar to what ljf suggests at the end of the previous comment, except I really don't think it's a good idea to try to automate this during the migration, and instead should be handled in the individual apps because of how specific this is to each app).

- for bozon and similar apps, it's a bit trickier considering the use of regexes. *Maybe* for bozon it can be done adding a second permission with `/index.php` but in the general case, it's not clear how to handle the regexes (for instance [the one in lstu](https://github.com/YunoHost-Apps/lstu_ynh/blob/master/scripts/install#L195)). C.f. also [this comment](https://github.com/YunoHost/yunohost/blob/stretch-unstable/src/yunohost/app.py#L246-L267) and ultimately the issue is that, in the current ssowat paradigm, one permission = one url = one tile. Maybe it's possible to hack something using the post-add/remove-permission hooks, checking if visitors is enabled/disabled, and enabling/disabling some corresponding unprotected_regex ...

- as far as a i can remember, part of the real, clean, long-term solution was to manage permission rules in ssowat's conf via a dictionnary of routes and allowed users / groups (though to be seen how to handle the tile list), which was something drafted by Josue. Maybe that's what https://github.com/YunoHost/SSOwat/pull/153 is about but I haven't had a deep enough look.

**Comment by kay0u** [comment]
> [...] I'm not sure that there is a way to adapt the code to get rid of these incompatibility [...]
 
I'm not 100% sure, but I think I found a solution here: 
https://github.com/YunoHost/SSOwat/commit/af892991afda2f8cd9449606bf8600838a931db8
The idea is to kept only the longest_match_skipped/protected/unprotected for the current url, and work with them.

> for dotclear2 and similar apps, the real fix imho is that the app should be updated to have a second permission corresponding to the admin panel [...] I really don't think it's a good idea to try to automate this during the migration

Ok with that, the problem with the current version is that the admin part is just unreachable for users as long as the app doesn't receive any update concerning the admin permission. Is it really what we want?

> for bozon and similar apps, it's a bit trickier considering the use of regexes. Maybe for bozon it can be done adding a second permission with /index.php but in the general case, it's not clear how to handle the regexes (for instance the one in lstu). C.f. also this comment and ultimately the issue is that, in the current ssowat paradigm, one permission = one url = one tile. Maybe it's possible to hack something using the post-add/remove-permission hooks, checking if visitors is enabled/disabled, and enabling/disabling some corresponding unprotected_regex ...

I implemented something like that here: 
https://github.com/YunoHost-Apps/lutim_ynh/pull/44
I think is not that far from a final version, and if everyone is ok with this workaround, we should write doc about this.

> as far as a i can remember, part of the real, clean, long-term solution was to manage permission rules in ssowat's conf via a dictionnary of routes and allowed users / groups (though to be seen how to handle the tile list), which was something drafted by Josue. Maybe that's what YunoHost/SSOwat#153 is about but I haven't had a deep enough look.

Uuh, YunoHost/SSOwat#153 is just trying to fix some bugs

**Comment by kay0u** [comment]
Fixed by https://github.com/YunoHost/SSOwat/pull/156
