### ISSUE TITLE
[debian] use salsa to build/check debian packages

### ISSUE THREAD

**Issue by arthurlutz** [YunoHost/issues#1508]
https://salsa.debian.org/ is a gitlab forge which is part of the debian infrastructure and allows guest account creation for non debian developers. 

They have a shared maintained pipeline for testing and building debian packages https://salsa.debian.org/salsa-ci-team/pipeline/ 

It would be nice if the yunohost project could use this for building debian packages. Maybe this could be a nice replacement or complementary to https://github.com/YunoHost/vinaigrette and https://github.com/YunoHost/cd_build

**Comment by arthurlutz** [comment]
Trying it out : 

* https://salsa.debian.org/arthurlutz-guest/yunohost-admin/merge_requests/1
* https://salsa.debian.org/arthurlutz-guest/yunohost/merge_requests/1
* https://salsa.debian.org/arthurlutz-guest/moulinette/merge_requests/1
* https://salsa.debian.org/arthurlutz-guest/ssowat/merge_requests/1
* https://salsa.debian.org/arthurlutz-guest/metronome/merge_requests/1

There are a few errors so far which I'll look into soon (if I get feedback for this it would help to know if this is useful for the project).

**Comment by arthurlutz** [comment]
So far : 

* yunohost-admin, build failing
* yunohost: build OK, some tests failing
* moulinette; build OK, only piuparts test failing (might be python2 related)
* ssowat : build OK, some tests failing
* metronome: build failing

**Comment by alexAubin** [comment]
Discussed quickly on the chat today, that sounds interesting and could reduce our cost of maintaining our custom build chain, so could be worth it to invest some time in it ...

Didnt check the logs to see exactly what happens, I'm suspecting there's some trick and changes to be done for yunohost-admin build to work because it needs to be able to `npm install` somehow ... (and for this I had to implement some epic dirty black magic in vinaigrette). I have no idea what's the right way to handle this.

(Also wondering how the signing and actual distribution of the packages would happen if we were to use this build chain)

**Comment by alexAubin** [comment]
btw Kayou was doing some tests the other day on salsa, for example https://salsa.debian.org/kayou-guest/yunohost/-/pipelines

**Comment by alexAubin** [comment]
Closing because that doesn't really sound worth it, rewrote Moulinette two years ago (https://github.com/YunoHost/vinaigrette/pull/5) , sbuild is much more robust and working ~smoothly
