### ISSUE TITLE
ssowat conf redirected_regex should redirect also root path

### ISSUE THREAD

**Issue by alexgarel** [YunoHost/issues#1514]
hi, this is the second time I install yunohost on a machine, and both time, I had to modify `/etc/ssowat/conf.json`

As yunohost, configures it, when a user log in, he is redirected to `/` which displays Ngnix default page ! And so the user is stuck there.

 indeed   `/etc/ssowat/conf.json` contains the following line:

```javascript
    "redirected_regex": {
        "myserver.noho.st/yunohost[\\/]?$": "https://myserver.noho.st/yunohost/sso/"
    },
```

I've changed this to

```javascript
    "redirected_regex": {
        "myserver.noho.st/yunohost[\\/]?$": "https://myserver.noho.st/yunohost/sso/",
        "myserver.noho.st[\\/]?$": "https://myserver.noho.st/yunohost/sso/"
    },
```

And this is far better.

Maybe the login page is wrong when redirecting to `/` but this settings is however more robust.

So in my opinion this is a bug.

**Comment by alexAubin** [comment]
Ugh thanks for you report ... that indeed looks like a bug that should be kinda easy to fix ... I guess we didnt notice it so much because usually we end up installing apps, but yeah ... Though I'm kind of surprised it's not somehow redirected by other rules ...

I don't know if the ssowat conf is the right place to fix it though ... Maybe the nginx conf would be a better place ... idk, it sounds like it depends wether or not you installed an app on the root or not ?

**Comment by selfhoster1312** [comment]
I think last time i installed Yunohost i was redirected to the admin panel. Is that right? If yes, we can probably close this issue.

**Comment by alexAubin** [comment]
Closing because after the SSOwat/portal refactor, there's no redirected_regex anymore
