### ISSUE TITLE
Remove hard-coded DNS servers from certificate.py

### ISSUE THREAD

**Issue by dlehmenk** [YunoHost/issues#1541]
I installed YunoHost on a VM at my university, which uses an internal DNS resolver. Because of this, the resolvers in certificate.py do not work. Despite using --no-checks, the script tries to contact ip.yunohost.org, which makes the process really slow. Also debugging the error was quite confusing, because I fixed the DNS config at system level, but the script failed, and I had to use --debug, be confused because DNS worked everywhere else and had to finally look into the code for the answer. I see that this is a special case, but I would appreciate it very much when the script would not override system settings silently. (Also for some reason the certificates can not be requested through the web interface ("domain doesn't seem ready"), which might be related, but I had not yet time to debug that.)

**Comment by alexAubin** [comment]
>I installed YunoHost on a VM at my university, which uses an internal DNS resolver. 

Uh can you elaborate on that ? There's a difference between "my ISP provides its own DNS resolver if I want to use it" and "my university blocks outgoing port 53 except to its own resolver" :/

> I see that this is a special case, but I would appreciate it very much when the script would not override system settings silently. 

I do agree with you ... The thing is that it's more complicated than just this, because this stupid /etc/resolv.conf is the subject of a war of many programs which want to inject their own thing in it. In the context of YunoHost, we have `resolvconf` (the service, not the file) making it point to 127.0.0.1 because we designed this around dnsmasq. But there are programs like NetworkManager or the dhcpclient inside Linux that may override /etc/resolv.conf, typically by your "evil" ISP DNS resolver which is for many likely to be a lying/censored/spying DNS resolver.

I'm actually curious to know how you managed to edit /etc/resolv.conf without having it being override by resolvconf (the service) ? Or did you edit /etc/resolv.dnsmasq.conf ?

**Comment by dlehmenk** [comment]
> > I installed YunoHost on a VM at my university, which uses an internal DNS resolver.
> 
> Uh can you elaborate on that ? There's a difference between "my ISP provides its own DNS resolver if I want to use it" and "my university blocks outgoing port 53 except to its own resolver" :/

Yes, for me it's the second one. From inside the network only the existing servers can be queried, everything else is blocked.

> > I see that this is a special case, but I would appreciate it very much when the script would not override system settings silently.
>
> [..] But there are programs like NetworkManager or the dhcpclient inside Linux that may override /etc/resolv.conf, typically by your "evil" ISP DNS resolver which is for many likely to be a lying/censored/spying DNS resolver.

I totally see that point, but in my case it is unforunately what I want/need. I'm also not complaining about this default, because I knew my network limitations and changed it. But why are the servers also hard coded in the certificate.py module?

> 
> I'm actually curious to know how you managed to edit /etc/resolv.conf without having it being override by resolvconf (the service) ? Or did you edit /etc/resolv.dnsmasq.conf ?

I first edited /etc/resolv.dnsmasq.conf, but then decieded that I probably don't need dnsmasq at all (somewhere in the documentation I found something like "you are free to use it or not") and disabled the dnsmasq service (maybe this has implications that I'm not aware of?). Without it resolvconf uses the resolvers DHCP sends, which has the advantage that they will be automatically updated, if they should change someday.

**Comment by alexAubin** [comment]
>But why are the servers also hard coded in the certificate.py module?

Because that's the way it was implemented in the first place and had no issue so far about it :sweat_smile: 

Also there are technical implications about querying the local system rather than a remote system such as : results being cached and therefore being annoying if you updated the DNS records but the system still has the old one, ooooor since we're using dnsmasq and dnsmasq resolves the local domain locally, it will find your current global ip because that's what our automatic configuration system puts in the file ... But the point of the test is precisely to test that the "real" DNS record in the "real internet" points to your current global IP. (Dunno if that make sense, this whole thing about DNS resolvers and diagnosis is a mess)

Anyway, I'm about to implement some change in that certificate thing to use the results from our new diagnosis system which should use less hard-coded DNS. To be more accurate, it will use the nameservers listed in /etc/resolv.dnsmasq.conf : https://github.com/YunoHost/yunohost/blob/stretch-unstable/data/hooks/diagnosis/12-dnsrecords.py#L20-L21

That should fix your specific issue under the condition that you put your resolver in /etc/resolv.dnsmasq.conf which is an acceptable thing to do from the point of view of our regen-conf system. Indeed there's a drawback that it won't get automatically updated by the dhcpclient, but on the other hand a dns resolver IP ain't supposed to change every day ...

**Comment by dlehmenk** [comment]
> Also there are technical implications about querying the local system rather than a remote system such as : results being cached and therefore being annoying if you updated the DNS records but the system still has the old one, ooooor since we're using dnsmasq and dnsmasq resolves the local domain locally, it will find your current global ip because that's what our automatic configuration system puts in the file ... But the point of the test is precisely to test that the "real" DNS record in the "real internet" points to your current global IP. (Dunno if that make sense, this whole thing about DNS resolvers and diagnosis is a mess)

Ah yeah, that's a good point. 
> 
> Anyway, I'm about to implement some change in that certificate thing to use the results from our new diagnosis system which should use less hard-coded DNS. To be more accurate, it will use the nameservers listed in /etc/resolv.dnsmasq.conf : https://github.com/YunoHost/yunohost/blob/stretch-unstable/data/hooks/diagnosis/12-dnsrecords.py#L20-L21

Nice, thank you :)

> 
> That should fix your specific issue under the condition that you put your resolver in /etc/resolv.dnsmasq.conf which is an acceptable thing to do from the point of view of our regen-conf system. Indeed there's a drawback that it won't get automatically updated by the dhcpclient, but on the other hand a dns resolver IP ain't supposed to change every day ...

Yes, I think it's not optimal, but should definitely work. Since DNS is sometimes really tricky, as you said, it's probably a good solution. I only think that it might be confusing when one disables dnsmasq that the file named ...dnsmasq.. is still a relevant config file. If it's not too much to ask, maybe rename it to resolv.yunohost.conf or make that a symlink to resolv.dnsmasq.conf (which would also allow for sysadmins to change it to point to the resolv.conf while keeping the original resolv.dnsmasq.conf)?

**Comment by alexAubin** [comment]
>I only think that it might be confusing when one disables dnsmasq that the file named ...dnsmasq.. is still a relevant config file.

Yeah I forgot to say that it implies to keep using dnsmasq ...

**Comment by alexAubin** [comment]
Closing because DNS_RESOLVERS got removed from certificate.py somewhere in the 3.7 i think
