### ISSUE TITLE
Making Metronome optional

### ISSUE THREAD

**Issue by rafoo** [YunoHost/issues#1574]
This is a follow-up of this discussion on the forum: https://forum.yunohost.org/t/why-does-yunohost-depend-on-an-xmpp-server/11021/2.

The aim of this issue is to track progress on removing the dependency to the Metronome XMPP server and only require it when it is actually needed.

PHP and MySQL could also be considered but let's focus on Metronome here.

**Comment by alexAubin** [comment]
I believe it would be indeed relevant to have some concept of "system modules" (or whatever you call this) that can be enabled / disabled. 

For example, we have the opposite situation for postgresql where it would be nice to have its configuration and other things managed by the regen-conf, and it would be useful to have this defined directly in the core ... but currently it's not possible because the regen-conf will assume that the corresponding system packages is installed. So far it's handled by the bash helpers but it remains a bit hackish and not practical when you need to push changes in the conf as it happened recently. And more and more I end up adding hacky patches in the python code like "if postgresql is installed" or "if service_name == postgresql" ...

Could also be a middle-ground for ljf's long-term wish to have openvpn / vpnclient installed by default (which I disagree with :sweat_smile: ) ... but would definitely make sense if this would be a module that can be enabled/disabled.

**Comment by alexAubin** [comment]
Merging with https://github.com/YunoHost/issues/issues/1578
