### ISSUE TITLE
Request to add Rsync

### ISSUE THREAD

**Issue by liberodark** [YunoHost/issues#1604]
Hi,

I would like rsync to be added to http://forge.yunohost.org/debian/
Rsync remains the most widely used protocol and a global standard for repository creation.
Of course there are scripts or applications that use rsync with specific parameters etc.
But the primary goal is to have an rsync server on the forge.
There are several reasons for this. But in any case it is a very good thing.
Be aware that ubuntu, debian, fedora, arch linux...etc uses rsync.
Despite other available tools all rests.
On this software.

best regards.

**Comment by alexAubin** [comment]
More generally, the question is how to support and document the creation of mirrors of our deb repository ... As discussed in private, many places in Debian's doc (like [here](https://www.debian.org/mirror/ftpmirror) and [here](https://salsa.debian.org/mirror-team/archvsync)) discourage the use of rsync and discourage writing any home-made tool ... 

>Be aware that ubuntu, debian, fedora, arch linux...etc uses rsync.

I don't know what you mean exactly by this, but the fact that you *can* rsync their repository does no mean that's the recommended way to proceed...

Edit: I see there's also an `apt-mirror` package that seems to be designed for exactly this

**Comment by liberodark** [comment]
Ubuntu and Debian use : https://apt-mirror.github.io/
Rsync is for other usage but is highly recommend to use.
Only need rsync other tools for is for more simple use.
Rsync is not really easy at all.
But it is better suited to specific needs, that's why everyone uses it.

**Comment by alexAubin** [comment]
Yes, I understand you *really* want to use rsync but you're not listening to what I'm saying.

I'm saying : 
- Debian's documentation explicitly state that using rsync or custom scripts should be avoided
- There are existing tools developed by the Debian's people to do this and they are more simple. I just tested `apt-mirror` and it took me literally five minutes to set it up

I understand that you have other scripts that deal with other repo and they use rsync and that's easier for your specific case to use a single tool for all distributions you maintain mirrors of. Yet, from my point of view, that's not enough for this project to implement something that Debian's documentation explicitly discourage to use. 

I'm not saying rsync is not a good tool, as it has hundreds of applications. But `apt-mirror` already works and is apparently the recommended way to proceed with mirror creation.

But who knows, maybe there's more to the story and in fact Debian's people are wrong to discourage the use of rsync, but these people also know what they're talking about, so that remains to be demonstrated ...

**Comment by liberodark** [comment]
only discourage the use of rsync if you don't know use it.

I already mentioned it in my previous message : 

> Ubuntu and Debian use : https://apt-mirror.github.io/
> Rsync is for other usage but is highly recommend to use.
> Only need rsync other tools for is for more simple use.
> Rsync is not really easy at all.
> But it is better suited to specific needs, that's why everyone uses it.

**Comment by alexAubin** [comment]
Well I doubt people from Debian don't know how to use rsync ... On the contrary I think they know how to use it, they've seen people using it, and they know it might leads to issue, which is why they discourage people from using it, especially considering that there are tools that are much simpler to use to create a mirror ...

**Comment by alexAubin** [comment]
Closing because as discussed this is not the right way to proceed
