### ISSUE TITLE
uwsgi-app@ffsync.service Statut dead 50 years ago

### ISSUE THREAD

**Issue by valderaplets** [YunoHost/issues#1618]
hi !

After a fresh install of ffsync :

![image](https://user-images.githubusercontent.com/63161106/82993069-51bce700-a000-11ea-892a-1a4860090791.png)
![image](https://user-images.githubusercontent.com/63161106/82993141-6c8f5b80-a000-11ea-8801-23f882488fd9.png)

:(

**Comment by alexAubin** [comment]
I know it's scary because it's red, but it's just a small bug between the app and yunohost fixed by https://github.com/YunoHost-Apps/ffsync_ynh/pull/20

If you upgrade the app this old service should automatically disappear/be removed (but the one without .service at the end is the right one and should stay)

Closing the issue since that should fix it, but feel free to complain if you want to reopen / continue the discussion

**Comment by valderaplets** [comment]
Oh okay it's in testing, i have to wait. Thx for help

**Comment by alexAubin** [comment]
Ah yes maybe it is, sorry

In the meantime you can safely click the "Ignore" button for that error
