### ISSUE TITLE
Old TLS protocols enabled and no TLS 1.3

### ISSUE THREAD

**Issue by DarkCoocky** [YunoHost/issues#1645]
Hello,
I was considering the idea of migrating from syncloud to YunoHost but i wanted to know how good it is about security.
So I tested the demo's server's security with Qualys (SSL Labs) and the report noticed some issues.
You can see the general report here:
![image](https://user-images.githubusercontent.com/68286576/88525842-aa9e0100-cfea-11ea-879d-24d75a54411b.png)

First of all, TLS 1.0 and 1.1 are enabled. These protocols are vulnerable and have bad performances. We should consider disabling it for everyone to increase the safety and performances.

About TLS 1.2 most of the cipher suites are weak and then should be disabled. The only one that's not weak is _TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384_.

The last point is to enable TLS 1.3 for everyone. It's the latest version of the protocol and then should have all these suite enabled to be able to use TLS 1.3 and 1.2 correctly :
ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;

**Comment by alexAubin** [comment]
Not sure why the demo still has TLS 1.0 and 1.1 enabled (maybe some reverse proxy stories idk) but since 3.8 only TLS 1.2 is enabled : https://github.com/YunoHost/yunohost/blob/stretch-unstable/data/templates/nginx/security.conf.inc#L13

TLS 1.3 ain't available because it requires nginx version from Buster (but Yunohost 4.0 release is around the corner)

And regardings ciphers and other tweaks we stick as much as possible to Mozilla's recommendations (not just for nginx)

Nevertheless, let me say that having shinny A+ on SSLlabs is not equal to having a secure server. Nor does having a B or lesser grade means that your server is insecure. There are hundreds of details regarding securities, many of them are often forgotten about (sometimes because counter intuitive), and a false sense of security is worse than no security at all (you seem to be a technical person so hopefully I'm not teaching you anything here).

**Comment by DarkCoocky** [comment]
For sure having a A+ doesn't mean absolute safety at all. The greatest weakness of a computer system is still the person sitting in front of the computer. But if we can suppress as many weaknesses as possible from the machines that's still a good thing.

By the way I'm not a technical person at all I'm an automation technician so server's security is not my job at all xD
