### ISSUE TITLE
Use yunohost on a different port than 443 does not work

### ISSUE THREAD

**Issue by erdnaxeli** [YunoHost/issues#1666]
The problem is the following : the port 443 on my public IP address is already used, and I can't use a reverse proxy.

I tried to redirect the port 4430 on my box (which have the public IP) to the port 443 on my yunohost instance in my local network, but it fail due to this line https://github.com/YunoHost/yunohost-admin/blob/f23e6aa14f0612e391e87bb39bbea52aab19096c/src/js/yunohost/helpers.js#L120. We can see here that the admin app is ignoring the location's port, so it make the requests to the same domain on port 443, which fails.

**Comment by erdnaxeli** [comment]
Looking at the code, I don't understand why it specifies the domain part in the URL. Making a call just to `/yunohost/api/…` should work (https://api.jquery.com/jquery.ajax/).

**Comment by alexAubin** [comment]
Might be fixed in the new version of the webadmin, but honestly I doubt it's a good idea to try to make Yunohost overall work with a different port. Too many pieces of codes and apps (or for example Lets Encrypt, though that's for port 80, not 443) are likely to assume that your server works with the default ports.

**Comment by alexAubin** [comment]
Closing / wontfix, running a webserver on another port than 80 / 443 is hell for many reasons ... also maybe the original issue got fixed in 4.2 during the rewrite of the webadmin idk
