### ISSUE TITLE
Support Debian 11 "Bullseye"

### ISSUE THREAD

**Issue by Neustradamus** [YunoHost/issues#1679]
Edit by @alexAubin to have a summary of the status

---

### Relevant links on Debian's side: 

- [List of pending blocking issues for Debian Bullseye release](https://deb.li/rcbugs)
- [Official Bullseye release note](https://www.debian.org/releases/bullseye/amd64/release-notes/)
- Comprehensive list of changes in Bullseye : https://michael-prokop.at/blog/2021/05/27/what-to-expect-from-debian-bullseye-newinbullseye/
- [Debian-devel-announce mailing list](https://lists.debian.org/debian-devel-announce/)

### Core support

- [X] Many tweaks and fixes to be able to run on Bullseye, on all 4 major yunohost packages
- [X] [Adapt the .deb build chain to build and serve bullseye builds](https://github.com/YunoHost/vinaigrette/commit/c19a5effdc8798296c43fa6d9a751804cd761690)
- [X] [Adapt install script](https://github.com/YunoHost/install_script/commits/bullseye)
- [X] Test fresh installs
- [X] [`bullseye`](https://github.com/YunoHost/yunohost/commits/bullseye) branch passes tests of the CI  
- [X] Looked at https://ssl-config.mozilla.org/ to check if some configs among nginx, ssh, dovecot, postfix should be upgraded with the new softwares and openssl version, found nothing
- [X] Dropped old legacy stuff as a general cleanup
- [x] Should check carefully the new default configs for every major service to check if there are new important options or default stuff (typically fail2ban)
- [ ] Maybe a weird issue with systemd services taking a weirdly long time to start idk
- [ ] Extensive checks of all the major features
    - [x] Certificate install
    - [x] Firewall
    - [ ] Fail2ban rules for ssowat, yunohost-api
    - [ ] Email send and receive, + dovecot
    - [ ] Specific apps like vpnclient + hotspot
    - [ ] ???
- [ ] ???
- [x] Wait for Debian Bullseye to actually be released as stable by the Debian project :wink: (early July ? idk, check the dev announce ML)
- [ ] Release as alpha, ... beta, ...
- [ ] Build new images for x86, RPi, armbian

#### Buster -> Bullseye support

- [X] [Implemented general migration](https://github.com/YunoHost/yunohost/pull/1242)
- [X] Implemented the php and postgresql migrations (N.B. this happens in the bullseye branch, not the migrate_to_bullseye branch)
- [X] Ran a basic migration with one PHP app (wordpress) and postgresql app (wikijs) as a basic validation of the migration
- [ ] Run a more complex migration + extensive tests after migration ?
- [ ] ???

### Apps

- [X] Bullseye test campaign ongoing on https://ci-apps-bullseye.yunohost.org/ for level 6+ apps
- [X] Comparison dashboard available at https://dash.yunohost.org/appci/compare/stable...bullseye
    - So far "only" about 30 broken apps among the 200+ apps tests
    - Half of them have ~easy fixes, the other half may be more complex or unsolvable as long as upstream projects don't support bullseye
- [ ] Fix TODOs for specific apps : https://github.com/orgs/YunoHost-Apps/projects/4

**Comment by Neustradamus** [comment]
@yunohost Team, @alexAubin, @decentral1se, @ericgaspar, @frju365, @JimboJoe, @julienmalik, @kay0u, @M5oul, @Psycojoker, @scith, @zamentur: Good news all,

We are at the Debian 11 first part freeze day! :)

Time to have several branches in YunoHost, the future of Debian will be:
- 9: Stretch (current old-stable) -> old-old-stable
- 10: Buster (current stable) -> old-stable (currently Yunohost "dev")
- 11: Bullseye (current testing) -> stable
- 12: Bookworm (do not exist yet at this time) -> testing
- sid: (unstable)

The goal is to be really ready and process to the migration easily in some months.

YunoHost current branches:
- dev: based on current buster
- 9: stretch-unstable
- 9: stretch-stable
- 9: stretch
- 8: jessie
- 7: wheezy

I propose you:
- To create a "buster" branch with current "dev" branch which will by the default branch
- To rename "dev" branch to "bullseye" branch which will be updated/ajusted with "Debian 11 testing" new packages

When Debian 11 will be official:
- Move the default branch to "bullseye"
- Create a new "testing" branch based on "bullseye" branch and updated/ajusted with new "Debian 12 testing" packages

Of course, the most important branch when Debian 11 will be official must be "bullseye".

**Comment by MX10-AC2N** [comment]
Hi, how can test Yunohost for debian bullseye ??

**Comment by alexAubin** [comment]
... You can't, except if that's for development and you're ready for many struggles and tweaks

**Comment by MX10-AC2N** [comment]
Thanks @alexAubin  
I was hoping for a next Debian Bullseye compatible release. Is this progressing well? Do you have any idea when this might be available?
I take this opportunity to thank the whole Yunohost Team for this superb tool that you have given us, thank you again because for a novice like me it was quite easy to set up and manage a web server at home .. Thank you ..

**Comment by alexAubin** [comment]
It is "progressing" .. kind of ... currently we moved to Python 3 (in yunohost 4.2, next version) which is a big requirement for Bullseye. We have some draft .deb builds for Bullseye. Maybe you can get it to install if you know your way in the super-unstable branch and stuff, but postinstall will still probably explode. But I was hoping to get a few peaceful days next week or next-next week to work on having a first working install script (just like the current install.yunohost.org) so that we can start iterating, identify and fix issues, etc ...

"When it'll be available" is basically "when it's ready" ... so far these last ~4 years we had a ~1 year lag between the Debian release (usually around june/july) and the migration upgrade.

This time we're trying to catch up and ideally have Yunohost ready for Bullseye maybe in july or august (also thanks to a support grant from Code Lutin, in particular for Python 3) but no guarantee, we're volunteers, etc, maybe tha'll be more like autumn or winter

Note that the complexity is that it's not just about "making Yunohost core python code work in Bullseye", that part is easy... We need to implement and test the migration from stretch->buster, and most importantly test entire app ecosystem (180+-whatever, i lost how many of these we have now) and fix as many regressions as we can - that part is a big chunk of the time it takes to make Yunohost (as an entire ecosystem) "Bullseye-ready"

**Comment by Neustradamus** [comment]
It is important to work on the current Debian testing (Debian 11 Bullseye is testing since 2019-07-06) before the release to have a perfect compatibility.

The goal is to release the version little time after, not like previous YunoHost.

Note:
- Debian 10 Buster has been released: 2019-07-06 (https://wiki.debian.org/DebianBuster)
- YunoHost 4.0 Buster has been released: 2020-07-29 (https://forum.yunohost.org/t/yunohost-4-0-buster-release-sortie-de-yunohost-4-0-buster/12195)

How many days after: 1 year and 23 days.

Like I have said, when Debian 11 will be released, Debian 12 will in testing.

The goal of testing is to inform people of changes and to test before the official release.

Time to enter in the future.

**Comment by alexAubin** [comment]
Status update : 

- tests on [the `bullseye` branch](https://github.com/YunoHost/yunohost/commits/bullseye) are mostly passing, thanks to Kayou
- started the app test campaign on https://ci-apps-bullseye.yunohost.org/ - so far only with level 8+ apps. So far the vast majority of issues found are easy to solve so that's pretty encouraging
- started a draft of buster -> bullseye migration here : https://github.com/YunoHost/yunohost/pull/1242 - so far some basic tests (LXC with no apps installed) are promising

TODOs : 
- get more results from the app ci, fix corresponding issues
- test at least all level 6+ apps
- manually test all major features on a yunohost install : cert install, smtp, imap, diagnosis, user portal, permissions, firewall, fail2ban, ...
- for some reason, `systemctl restart` appears to be super slow, which makes postinstall / regenconf super long. Not sure what's happening, systemd seems to wait for some service stop timeout ...
- implement the "usual" migrations for php 7.3 -> 7.4 and postgresql 11 -> 13, based on similar migrations for jessie->stretch and stretch->buster
- ???
- profit!

**Comment by alexAubin** [comment]
Randomly wandering on the internets, found some interesting read:
- https://deb.li/rcbugs / the list of pending blocking tickets for Bullseye release (42 at the time of writing this)
- A comprehensive list of changes in Bullseye : https://michael-prokop.at/blog/2021/05/27/what-to-expect-from-debian-bullseye-newinbullseye/ , among which I found : 
   - shipped kernel to be 5.x compared to 4.x - i don't know how that affects upgrades from buster
   - support for includes in sshd_config, at last ! https://manpages.debian.org/testing/openssh-server/sshd_config.5.en.html#Include_/etc/ssh/sshd_config.d/*.conf
   - a bunch of possibly new interesting stuff in systemd and apt
- Change in the [debian security line format in sources.list](https://www.debian.org/releases/bullseye/amd64/release-notes/ch-information.en.html#security-archive), c.f. issue spotted in my previous post
- Further announcements to arrive in https://lists.debian.org/debian-devel-announce/ during June I suppose

**Comment by alexAubin** [comment]
Edited the original post with current status

**Comment by alexAubin** [comment]
Debian announced Full Freeze to start on July 21st, and there are internal discussions for a \*possible\* release on July 31st

**Comment by alexAubin** [comment]
Bullseye is full freezes : https://lists.debian.org/debian-devel-announce/2021/07/msg00002.html

**Comment by Neustradamus** [comment]
Note: Official Debian 11.0 "Bullseye" stable release date : 2021-08-14:
- https://lists.debian.org/debian-devel-announce/2021/07/msg00003.html

**Comment by alexAubin** [comment]
Bullseye got released :+1:

**Comment by alexAubin** [comment]
By the way I'm reading that : 

https://www.debian.org/releases/bullseye/amd64/release-notes/ch-information#ssh-not-available

No new SSH connection can be established during the upgrade

We should probably warn about this in the migration disclaimer

**Comment by Neustradamus** [comment]
@alexAubin: Maybe good to do:
`If the upgrade is being carried out over an SSH connection which might be interrupted, it's recommended to upgrade openssh-server before upgrading the full system.`

**Comment by Neustradamus** [comment]
@alexAubin: Have you progressed?

**Comment by kay0u** [comment]
@Neustradamus and you?

**Comment by rysiekpl** [comment]
Any news on this? No pressure, just curious. 😃

**Comment by alexAubin** [comment]
We're going for a 4.3 testing in a few days before starting Bullseye alpha campaign, ideally around the end of the month

**Comment by Neustradamus** [comment]
@alexAubin: Have you progressed?

**Comment by alexAubin** [comment]
No, and you don't seem to understand how much "contributing" exclusively by randomly pinging volunteers every 3 months is a problem.

Considering that we already highlighted this fact to you, I'm blocking you.

(Also to be extra clear : this is the top priority issue next to releasing 4.3 so there's no need to remind anybody about it)

**Comment by jcn50** [comment]
@alexAubin Why did you block the person that opened the issue?.. I don't think it is nice~ you should take it easy on people you know. Maybe the guy has donated financially to the project (on the top of his time), how could you know?..

**Comment by alexAubin** [comment]
Take it easy on people ? Funnily that's exactly what it is about, yes.
- Neustradamus has been regularly and randomly pinging people to know the status of issue, which really sounded like putting the pressure on specific people so that the issue he was interested in would progress or idk.  Also comments similar to something like "Omaged look it's been X days since release Y was released what are you doing !?!?!".
- He also submitted weird un-understandable issues, and despite our repeated attempt to understand what they were about, only provided elusive answers
- Several warnings have been made to stop randomly pinging people, and explaining that putting the pressure on volunteers was not okay. Same attitude continued. After he got banned from github, he continued this attitude on the forum. Same thing, explaining that putting pressure on volunteers was not okay, and unable to understand or even acknowledge that there's an issue.

Hence the ban, yes. Also donating to the project (assuming that was the case, but it doesn't matter) doesn't provide the right to put pressure on volunteers.

So once again, maybe people could stop the drama, acknowledge that this is a volunteer-driven project, acknowledge that putting pressure on people in counter productive, and acknowledge that things are not going to go faster by asking "what's the status" but by instead finding people with time and energy to contribute.

**Comment by alexAubin** [comment]
Alpha-stage was released (though not the migration part yet) : https://forum.yunohost.org/t/alpha-stage-testing-for-yunohost-11-0-on-debian-bullseye-and-migration-that-will-be-shipped-in-yunohost-4-4-x/18014

**Comment by biva** [comment]
Congrats!!!!!

**Comment by alexAubin** [comment]
The migration part was released in unstable, see previous topic link for instructions for whoever is willing to test it

**Comment by alexAubin** [comment]
Aaaand we're now moving to beta: https://forum.yunohost.org/t/beta-stage-testing-for-yunohost-11-0-bullseye-and-buster-bullseye-migration/18531

**Comment by alexAubin** [comment]
Closing as we're now in beta so that somehow addresses the issues of "Supporting Bullseye"

Remaining specific todos are in https://github.com/orgs/YunoHost/projects/10
