### ISSUE TITLE
Migration 19 fails with Permission ''nextcloud.legacy_skipped_uris'' already exists

### ISSUE THREAD

**Issue by DetermineAbsurd** [YunoHost/issues#1723]
Log found [here](https://paste.yunohost.org/raw/ziqakupofa). This seems to also be causing all of my apps to not have the ability to be labeled, however, I'm not sure if that is a related thing that this migration is supposed to fix.

**Comment by alexAubin** [comment]
Is this still an issue or did you work around it ?

Otherwise I would naively ask what happened on the system *before* this ... did the migration already run prior to this and failed for some other reason ..? Maybe a workaround can be to remove the line corresponding to "skipped_uris" in /etc/yunohost/apps/nextcloud/settings.yml and rerunning the migration ...

**Comment by DetermineAbsurd** [comment]
I seem to have fixed that issue with a work around by just backing up and restoring the app. Now the issue I have is that it's saying I can't run the migration because my domain doesn't exist. It also seems to have replaced the dashes in my domain with periods, as if it were a subdomain, i.e. `YunohostError: Domain 'aaa.bbb.ccc.ddd' unknown` instead of `aaa-bbb-ccc.ddd`.

**Comment by DetermineAbsurd** [comment]
Update to this. Seemingly it was a misconfiguration with one of my installed apps. It was using either an outdated or misconfigured configuration that was causing the failure. I was able to find the problem on this forum post [here](https://forum.yunohost.org/t/tools-migrations-migrate-failed-because-of-a-remaing-earsed-domain/13896). The grep didn't work, but manually going through the configurations yielded that the LSTU app had a broken configuration, causing the failure.
