### ISSUE TITLE
Option to back up settings and DB, but not data that is_big

### ISSUE THREAD

**Issue by kuba-orlik** [YunoHost/issues#1751]
I'm backing my server up with `restic`. The scenario I'm going for is to tell `yunohost` to backup everything as uncompressed files into `/backup`, run `restic` and delete the `/backup` dir.

I have two apps that store large amount of data - Syncthing and Peertube. Backing them up means copying ALL of their files into the `/backup` dir, which is unnecessary, as I could just tell `restic` to include `/home/yunohost.app` in the snapshot that it sends to the remote origin, and that'd greatly increase the speed of the backup (no need to copy those huge files to `/backup`) and help me use less HDD.

We already have an option to skip *all* data by specifying `do_not_backup_data=1`. I propose to add `do_not_backup_big_data`. Peertube_ynh already marks the data directory as `is_big`, so it wouldn't even have to be adjusted.

I can create a PR with such feature if you think that this is not a terrible idea.

**Comment by alexAubin** [comment]
Eeeeh I'm not sure to get it, `do_not_backup_data` already skip (only) the files flagged as is_big (at least that's what I can read from the code)

So what would be the difference between `do_not_backup_data` and `do_not_backup_big_data` ?

**Comment by kuba-orlik** [comment]
As @alexAubin  explained, `BACKUP_CORE_ONLY` already solves that. 

I guess i had that belief that it causes only ynh core settings (not apps) to be backed up and never challenged that. 

Thanks for your time!

**Comment by alexAubin** [comment]
eh yeah now that you mention it that semantic is disastrous because "CORE" can be understood as "all the yunohost system stuff" instead of "the 'core' part of the app, meaning not-the-big-data"

Anyway, we were in fact discussing this earlier with another contributor, and there's definitely some improvements to be made to the semantic and interface. That `BACKUP_CORE_ONLY` thing is just yet another hack that was kinda temporary and ended up becoming permanent - one main issue is that it's poorly documented and simply not available in CLI if you don't know about it (it's not in `--help`) nor in the webadmin ... we should have a proper mecanism to tell that we want to backup no large data at all, or some large data for specific apps, etc ...
