### ISSUE TITLE
The YunoHost API is not responding after upgrading to 4.2.4

### ISSUE THREAD

**Issue by tio-trom** [YunoHost/issues#1793]
### My YunoHost server

**Hardware:** VPS bought online 
**YunoHost version:**  4.2.4 
**I have access to my server :** Through SSH | through the webadmin | direct access via keyboard / screen | ...
**Are you in a special context or did you perform some particular tweaking on your YunoHost instance ?** : no

### Description of my issue

After the system upgrade, I got this error:
> YunoHost API is not responding
> **Error**: `"502" Bad Gateway`
> 
> **Action**: `"GET" /yunohost/api/installed?locale=en`
> 
> **Error message:**
> 
> The YunoHost API is not responding. Maybe 'yunohost-api' is down or got restarted?

![image|690x370](upload://5sCQmrKPeQfdE8QY4KEexYxbN6P.png)

I tried restarting the api service but although it says "success", it does not fix the issue.

```
/importlib/_bootstrap.py:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 152, got 144
  return f(*args, **kwds)
/usr/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 152, got 144
  return f(*args, **kwds)
/usr/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 152, got 144
  return f(*args, **kwds)
/usr/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 152, got 144
  return f(*args, **kwds)
/usr/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 152, got 144
  return f(*args, **kwds)
Success! Service 'yunohost-api' restarted

```

Rebooted the server too, but that didn't fix it.

I got the same exact error on a second server a few hours ago, and a server reboot fixed it. But not on this server...

**Comment by DansLeRuSH** [comment]
I got the exact same issue/context :(

**Comment by alexAubin** [comment]
See https://forum.yunohost.org/t/the-yunohost-api-is-not-responding-after-upgrading-to-4-2-4-greenlet-greenlet-size-changed/15674 for discussion and fix

**Comment by carrabelloy** [comment]
![image](https://user-images.githubusercontent.com/1060591/118930223-c42b8300-b945-11eb-996f-edbd36fc5bdd.png)
The API connection from the server to the software has not been running properly for a long time. Though, DNS set correctly. Some of the programs are still running. From the application side, not all of them and they remain, as on the next screen.
I hope it's not too much, but I'll pass on my English with a translator and pictures. With the hope that this problem will be solved.
![image](https://user-images.githubusercontent.com/1060591/118930256-cf7eae80-b945-11eb-8a79-49e4dde2a33a.png)
![image](https://user-images.githubusercontent.com/1060591/118930364-f0df9a80-b945-11eb-9721-41a8b87461ca.png)
Die Api Verbindung vom Server zur Software läuft nicht mehr sauber schon seit längerem. Obwohl, DNS richtig gesetzt. Ein Teil an Programmen läuft noch einigen. Von Anwendungsseiten her nicht alle und sie bleiben, so wie auf dem nächsten Screen.
Ich hoffe es sind nicht zu viel, doch mein Englisch gebe ich hier noch mal mit Übersetzer und Bildern weiter. Mit der Hoffnung das dieses Problem gelöst wird.
The API connection from the server to the software has not been running properly for a long time. Though, DNS set correctly. Some of the programs are still running. From the application side, not all of them and they remain, as on the next screen.
I hope it's not too much, but I'll pass on my English with a translator and pictures. With the hope that this problem will be solved.

**Comment by tituspijean** [comment]
> I hope it's not too much

@carrabelloy, it *is* too much. You are copy-and-pasting your issue in all possible venues. That is spam-like, and you seem not to have even read them. Have you followed the solution proposed above, in the forum thread I have already linked to you [there](https://forum.yunohost.org/t/system-youno-host-aim-not-api-found/15890/3?u=tituspijean)?

**Comment by carrabelloy** [comment]
#1807 If, one whole about a Backup sees tried one what happens in the upper picture. Luck has appear sometimes. As next mastodon. 
I have thought if he has all at once so much DNA problems that I have also not done, this points through this with different Horster lie and here three IP addresses exist, because here from my small Hoster and two other Hostern Domains on my server run. The vote problems I have gone and has altered new from the whole Domains as head Domain. Because I can afford this, head and no Sub-Domain increases in addition do or name can. 
Now had got to extinguish mastodon and wanted to play in the Backup. What does not go. 
I can also access on my terminal if somebody can say to me what one now with pleasure also about terminal which also runs it with me what has tried to prevent, actually, the script of Yunohost. However, thus often as I have installed the whole one here and have produced again and work reingesteckt has it would be nice with more than 160 GB if the system becomes able of run again. If I excuse works with more translated
