### ISSUE TITLE
updating without backup

### ISSUE THREAD

**Issue by brunovianna** [YunoHost/issues#1840]
### Describe the bug

When I try to update my Funkwhale app using yunohost cli, the script hangs because it tries to backup the whole music library and there is not enough space in my system.

I posted this question on the forum about a week ago and had no solution: https://forum.yunohost.org/t/is-it-possible-to-upgrade-without-backup/16563
I think there should be an option to backup the data or not. Even if I had enough space, it wouldn't be practical to backup all the music library just for an update. When I update other data intensive app such as nextcloud, this doesn't happen.

I don't think this is the same fixed in #1833 , since it dealt with the space taken up by the application files and this deals with the space used by the data library files. 

### Context

YunoHost version: 4.2.6.1 (stable)
I have access to my server : Through SSH
Are you in a special context or did you perform some particular tweaking on your YunoHost instance ? : My music collection is in an external hard drive, symlinked from /var/www/funkwhale/media
Funkwhale version: 1.0.1 

### Steps to reproduce

- *If you performed a command from the CLI, the command itself is enough. For example:*
    ```sh
     yunohost app upgrade funkwhale

    ```

### Logs

Log: https://paste.yunohost.org/raw/erukewebar

The update stops at the last line:
`rsync -a /var/www/funkwhale/media/ /home/yunohost.app/funkwhale/data/media/`

**Comment by alexAubin** [comment]
After discussing this specific situation with the maintainer of funkwhale_ynh : this is due to a misdesign of the initial funkwhale package (the media collection should always have been in `/home/yunohost.app/funkwhale` insead of `/var/www/funkwhale`, precisely to avoid huge backups)

The most simple solution to fix your issue which may be due to having an important media collection that can't be rsync for some reason is to : 
- manually backup the collection somewhere else
- uninstall funkwhale + remove the collection
- reinstall funkwhale and reimport the collection

There's indeed a more general question of being able to backup without the data which is partially solved using a somewhat hidden option, something that looks like `NO_BACKUP_UPGRADE=1` ... We should definitey add a proper option like `--no-safety-backup` to `yunohost app upgrade` command

Will open a follow-up ticket

**Comment by brunovianna** [comment]
Thanks
