### ISSUE TITLE
Port 25 is not detected correctly

### ISSUE THREAD

**Issue by eddinett** [YunoHost/issues#1870]
### Describe the bug

Yunohost tells me that port 25 outgoing is blocked and therefore no mails can be sent to other servers. It is true that mails do not arrive at other servers, but port 25 is not blocked by server provider. That's why I suppose there is a bug in Yunohost system.

### Context

- Hardware: VPS bought online
- YunoHost version: 4.2.8.1 (stable)
- I have access to my server: Through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no

### Steps to reproduce

   1. Go to Diagnosis
   2. Scroll to Email
   4. The SMTP mail server cannot send emails to other servers because outgoing port 25 is blocked in IPv4/IPv6.

### Logs

(not available)

Screenshot of the error message:
![Screenshot at YunoHost Admin](https://user-images.githubusercontent.com/82827440/131579992-12b0efb4-ba08-440a-99a9-5e4f8e5c34c5.png)

And the Screenshot of the Firewall settings of my Hosting provider (the port 25 is open!)
![Screenshot at Hetzner Cloud](https://user-images.githubusercontent.com/82827440/131580241-4c0363e7-3173-4b9e-a879-236154ee40de.png)

**Comment by alexAubin** [comment]
Hmokay I would trust more the yunohost diagnosis regarding port 25 rather than your hosting provider interface ... Sometimes port 25 has a special internal rule, or is handled in some other part of the interface, even if you explicitly have no rule in your firewall about it ...

Do you have any mean to be absolutely sure that port 25 ain't blocked ...?

**Comment by eddinett** [comment]
I'm sorry, my fault. I found the problem. Still thank you! :)
