### ISSUE TITLE
Docs: How to activate "sudo" for normal SSH user?

### ISSUE THREAD

**Issue by jedie** [YunoHost/issues#1875]
Think https://github.com/yunohost/doc/blob/master/pages/01.administrate/06.overview/04.commandline/ssh.md should include the information about how to allow "sudo" for a normal SSH user.

I didn't find it in the docs.

I use `usermod -aG sudo <username>` for this.

**Comment by alexAubin** [comment]
(In the future™ once we get rid of the infamous admin user, we shall have an admins group which should be sudo-allowed)

**Comment by scottwh** [comment]
> I use `usermod -aG sudo <username>` for this.

An alternative is to use phpLDAPadmin, which might be more future-proof. Log in with DN "cn=admin,dc=yunohost,dc=org" and the admin password. Find the branch for "ou=sudo". That has one object "cn=admin". Screenshot that for reference. Make a new object using the "Default" template. Pick objectClass sudoRole. Set  cn to be      \<your login\>. Copy the other attibutes from the "ou=sudo" object, but consider setting sudoOption to "authenticate" rather than "!authenticate".

**Comment by alexAubin** [comment]
Closing because new admins group merged in 11.1
