### ISSUE TITLE
DNS registry config : use glob instead of listing subdomains

### ISSUE THREAD

**Issue by Salamandar** [YunoHost/issues#1920]
I just tried the automatic DNS registry configuration. It works amazingly fine !

But i've got an issue with this: Until now, a glob was used for all the subdomains. That allowed a compact registry and an easy manual edition if required.

The automatic configuration lists all the domains instead, duplicating the configuration for each subdomain! That means that my 10-line config is now 40 lines long !!

It would probably be better to rollback to a glob config.

What do you think ?

**Comment by alexAubin** [comment]
The whole story about subdomain is still to be improved but basically the point of adding A records for subdomains in the parent domain config was to simplify the whole thing instead of being like "yeah, you should go in *every* subdomain DNS conf and implement *all* the records" etc. (and this also has implication on the diagnosis if I remember correctly)

As far as I know, the wildcard is still there and is enough if you don't want to implement all of the records (but using the wildcard also has its own issues)
