### ISSUE TITLE
ssh login possible althought `PasswordAuthentication no`

### ISSUE THREAD

**Issue by AkselRocks** [YunoHost/issues#1938]
### Describe the bug

ssh login with password possible althought `PasswordAuthentication no`

### Context

- Hardware: VPS bought online 
- YunoHost version: 4.3.4.1
- I have access to my server: Through SSH 
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: yes
  - If yes, please explain: change in ` /etc/ssh/sshd_config` -> `PasswordAuthentication no`

### Steps to reproduce

- Edited ` /etc/ssh/sshd_config`
```
Match Group sftp.app,!ssh.app
    PasswordAuthentication no
```
plus added in the file end:
`PasswordAuthentication no`

- as root: `systemctl restart ssh`
- I still can login via `ssh admin@serverdomain.xx` and typing the password

### Expected behavior

I expect, that I can not login with password.

**Comment by alexAubin** [comment]
When adding this line at the bottom of the file, it will end up in a `Match` section, and won't have a global effect : https://github.com/YunoHost/yunohost/blob/dev/data/templates/ssh/sshd_config

(Note that indentation is here only to simplify reading the file but isn't an actual logic like in Python)

Closing because this is a misunderstanding of sshd_config syntax, not a yunohost issue
