### ISSUE TITLE
php8.0-fpm service showing php7.3 logs

### ISSUE THREAD

**Issue by ericgaspar** [YunoHost/issues#1940]
php8.0-fpm service is showing php7.3 logs instead of php8.0 logs

![Capture d’écran 1](https://user-images.githubusercontent.com/46165813/145184784-166d0e08-ffbb-4307-b9f8-e34fec6c461d.png)

**Comment by alexAubin** [comment]
Zblerg, this is probably due to https://github.com/YunoHost/yunohost/commit/47f3c00d0c1ef3ce65cd7768b38526cb2b02a9b6 which was spotted by titus a few days ago

Unfortunately there's no easy way to fix this for setups where that already happens

Though it will be implicitly fixed by Bullseye, because I reworked the way the helper works and the phpX.Y-fpm are going to be dynamically added to the service list based on what packages are installed (zblerg that's difficult to explain but basically that's more magic & robust)

**Comment by ericgaspar** [comment]
Yes, I can confirm, the issue is gone with Bullseye
