### ISSUE TITLE
Improve benefit of diagnostic mail

### ISSUE THREAD

**Issue by rndmh3ro** [YunoHost/issues#1988]
Currently if the diagnostics-cronjob detects a problem, all we get in the mail is `Running the automatic diagnosis failed miserably`.

However I sometimes have the problem that the detected error is only temporary (e.g. disk space) so when I run the diagnostic in the frontend, no error is shown.

Therefor I propose to make the error-mail more useful by including the actual output of the diagnosis-run.

**Comment by alexAubin** [comment]
The diagnosis already sends an email of human-readable issues ... If you're seeing `Running the automatic diagnosis failed miserably.` then that suggests an unexpected crash in the code in which case you should share the details (how did you know it was only about disk space ? Or maybe indeed if disk space is full, yunohost can't run commands at all because it usually wants to log stuff, but that's a special edge case .. and that's why yunohost tries to warn about disk space getting low ...)
