### ISSUE TITLE
clients / resellers as well other features

### ISSUE THREAD

**Issue by zNight-lab** [YunoHost/issues#2001]
i wanted to know will there be any plans to add a few things

- clients side, where they can install there own apps, as well file manger, sql, sql phpmyadmin, webmail, ssh
- resellers to resell the client area where they can host there selfs.
- billing / invoice plugin, as well turn on and off features.. add software like CMS, forums, social network scripts
- real time stats

**Comment by alexAubin** [comment]
What do you mean ... do you want to transform Yunohost into a SaaS platform or something

**Comment by zNight-lab** [comment]
dang that was a fast reply :O haha

i mean, just like on how cPanel as it, where you can offer hosting plane to clients if that makes scene
where the client comes to the site, buys owncloud drive, or buys web site space to use on our servers..

**Comment by alexAubin** [comment]
Uh okay, didnt know cPanel allowed this, but I very much doubt that this is what Yunohost is about in terms of scope / spirit ...

**Comment by zNight-lab** [comment]
well i mean like if you go to cPanel, there site, and see how it works, i thought many yunohost can be like them, offer the same thing, and yeah i get its solo panel, but i'm sure others will want something for there friends or family to host on there servers... 

just a idea, does not mean it will happen, but never know

**Comment by alexAubin** [comment]
YunoHost is multi-user and the idea is that you (the admin) host a bunch of services for those people. Some people also use it in professional contexts as an ease to setup services (and related stuff such as backup) for clients. Some other people use it for school by providing hundreds of students with stuff. So it's not exactly "solo".

In terms of spirit, the Yunohost is more about making it so easy to host your own stuff and therefore not having to depend on third parties, rather than encouraging you to become a third party yourself. (There's a lot you could argue about this in terms of realistic-ness and strategy though but that's for another day). In terms of technical scope, the entire "sell stuff" with all the implications in terms of ui, payment/invoicing, security, is just completely out I think ... (like the scope of the project is already too huge compared to what we're able to achieve)

**Comment by zNight-lab** [comment]
ah i see, but u think they will add in PHP? where we can install custom CMS that needs php7,8 with exts and sql 

i like the software, and it as lot to offer, just wishing i can do more on the panel.. 
and i do agree on what your saying to

**Comment by alexAubin** [comment]
Not sure what you mean, PHP is a free/open programming language ? It's like asking if concrete will sell bathrooms ?

**Comment by ericgaspar** [comment]
[my_webapp](https://github.com/YunoHost-Apps/my_webapp_ynh) is what you need
