### ISSUE TITLE
Matrix-Synapse and Mastodon conflict when Mastodon is installed on root domain

### ISSUE THREAD

**Issue by project9501** [YunoHost/issues#2016]
Matrix-Synapse by default publishes a .well-known on the root domain regardless of whether it is installed to a subdomain, and Mastodon doesn't permit any changes to the domain it's installed on.  You can work around this issue by installing Synapse first and then Mastodon, but this makes upgrading Synapse impossible without uninstalling and then restoring Mastodon.

As Synapse provides an alternative discovery path via DNS records, one solution might be to implement a toggle in the Synapse installation script to bypass the .well-known and require the DNS record.

Note that this issue only arises when Mastodon is installed on the domain root.  If Mastodon is installed on a subdomain this issue does not appear, but then you're stuck with @sub.mydomain.tld as our Mastodon address and nobody wants that.

**Comment by Bugsbane** [comment]
I'm not sure, but it seems like it might be the same issue [mentioned here](https://github.com/YunoHost-Apps/synapse_ynh/issues/252) when Nextcloud is on the root.

Similar to the OP, I have Synapse on a subdomain, just with Nextcloud on root. It also ran into issues upgrading. Then after uninstalling, it also wouldn't allow reinstalling Synapse with the root domain for users, complaining that the domain already had Nextcloud installed on it.

This same setup was working perfectly before the synapse upgrade (which like the OP had Synapse installed first).

Setting synapses user domain to be something other than root allowed installing, but changed all the synapse users to @username:synapse.domain.tld  instead of @username:domain.tld

**Comment by Bugsbane** [comment]
Is there any further info I can provide to help with this? It's still an issue, and now there's what looks like a duplicate over at https://github.com/YunoHost-Apps/synapse_ynh/issues/323. @Josue-T the Ynh_Synapse maintainer seems to think that it's likely that the issue is upstream. If there's anything I can do to help triage/troubleshoot this, just let me know!

**Comment by Josue-T** [comment]
The issue is that while we have the installation of synapse no path is specified because it must be `/_matrix` and yunohost consider that synapse would like to use the root path as it's not specified in the `manifest.json`. After the app was installed the permission say that it's not the root path which is used but the subpath `/_matrix` so yunohost accept an other app to be installed.

**Comment by Bugsbane** [comment]
SO, is this a Yunohost issue, a synapse_ynh issue, or a mix of both? 🤔

**Comment by ketsapiwiq** [comment]
Maybe it's a YunoHost packaging issue, so that there's a mechanism to handle special routes (e.g. on the root domain like `.well-known` etc.) in the app manifest (and implement it in the bash scripts for install, upgrade, etc.)?  

Kinda related: https://github.com/YunoHost/issues/issues/1614

**Comment by alexAubin** [comment]
Related : https://github.com/YunoHost/issues/issues/684

**Comment by Bugsbane** [comment]
So, if I can just check that I'm understanding this correctly... the problem here is that both Synapse and Nextcloud (and some other apps like Baikal) all want exclusive control over some folders in the root domain, such as .well-known. Is this right?
