### ISSUE TITLE
Support Debian 12 "Bookworm"

### ISSUE THREAD

**Issue by alexAubin** [YunoHost/issues#2050]
#### :warning: Thread policy : following past traumas, we will not hesitate to remove any comment which do not add anything constructive on making progress with this, such as asking "Any update on this ?", "What is the ETA ?", "Bookworm is soon to be released", "Bookworm has been release for X days zomg 1!?!!", etc. We are a volunteer team, we will release stuff when it's stable, and you are welcome to effectively help us getting shit done, but for the love of god don't pressure volunteers as if they owe you something

---

### Relevant links

- [What's new in Bookworm](https://www.debian.org/releases/bookworm/amd64/release-notes/ch-whats-new.en.html) (doesnt seem super up to date, the version table thingy seems to be copypasta from Bullseye)
    - Expect [Python 3.11](https://packages.debian.org/fr/bookworm/python3), [PHP 8.2](https://packages.debian.org/fr/bookworm/php/php), [Postgresql 15](https://packages.debian.org/bookworm/postgresql)
- [List of pending blocking issues for Debian Bookworm release](https://deb.li/rcbugs)
- [Issues/changes to be aware of for bookworm](https://www.debian.org/releases/bookworm/amd64/release-notes/ch-information.en.html#openldap-2.5)
- [Debian 12 Bookworm's Installer Updated To Better Handle Non-Free Firmware](https://www.phoronix.com/news/Debian-12-Installer-Alpha-2)
- [Bookworm release expected on June 10th](https://lists.debian.org/debian-devel-announce/2023/04/msg00007.html)
- [Github project to track the progess](https://github.com/orgs/YunoHost/projects/19)

## Core TODO

- [x] Spin a bookworm LXC container, try to build/install YunoHost in it, fix shit until it kind of works
- [x] Adapt [the .deb build chain](https://github.com/yunohost/vinaigrette) to build and serve bookworm builds
- [x] Adapt [the install script](https://github.com/YunoHost/install_script)
- [x] Make the bookworm branch pass test on the CI
- [x] Look at https://ssl-config.mozilla.org/ to check if some configs should be upgraded with the new softwares and openssl version, among 
     - [x] nginx, 
     - [x] ssh, https://infosec.mozilla.org/guidelines/openssh
     - [x] dovecot, needs to add a 'modern' config https://ssl-config.mozilla.org/#server=dovecot&version=2.3.19.1&config=modern&openssl=3.0.8&guideline=5.6, -> but this is kinda a "new feature", not really mandatory to have it integrated ...
     - [x] postfix 
     - [x] ???
- [x] Look for old legacy stuff in the core that can be dropped out
- [x] Add backup/restore test for archives from the 11.x era
- [ ] Should check carefully the new default configs for every major service to check if there are new important options or default stuff (typically fail2ban)
- [ ]  Extensive checks of all the major features
     - [ ] Certificate install
     - [ ] Diagnosis
     - [ ] Firewall
     - [ ] Fail2ban rules for ssowat, yunohost-api
     - [ ] Email send and receive, + dovecot
     - [ ] Specific apps like vpnclient + hotspot
     - [ ] ???
- [x] Wait for Debian Bookworm to actually be released as stable by the Debian project wink (early July ? idk, check the dev announce ML)
- [ ] Release as alpha, ... beta, ...
- [ ] Build new images for x86, RPi, armbian
- [ ] rspamd/openDKIM? we want to remove rspamd but rspamd is responsible to sign emails with DKIM
    - [ ] decide if we remove rspamd
    - [ ] if we remove it, use openDKIM to do DKIM signatures for emails

### Major stuff to change in YunoHost ? 

- [x] Remove php, mysql and metronome from default installs (they are actually only in 'Recommends' since bullseye)
- [ ] Switch to `aptitude` instead of `apt`, at least for the migration procedure, to avoid all the apt/dpkg hell being absolutly stupid at resolving complex situations ...

### Bullseye -> Bookworm support

- [x] Implement the general migration (in a migrate_to_bookworm branch, to be merged in dev = current bullseye branch)
    - https://github.com/YunoHost/yunohost/pull/1759
- [x] ~~Implement the php migration (in the bookworm branch)~~
    - actually we could very well not have a php migration because nowadays Sury offers way more flexibility (every php versions from 5.6 to 8.3 can be installed even from Bookworm) and most apps are already using PHP8.x, only a handful are still using 7.x) 
- [ ] Implement the postgresql migration (in the bookworm branch)
- [ ] We'll probably want the "rebuild Python venv" thing too
- [ ] Test the whole "basic" migration process on different servers, not just x86 but also ARM/RPi
- [ ] Test migrating a more complex setup with a bunch of apps, including PHP ones, Python ones, Nodejs ones, Postgresql, Mysql, ...

### Apps

Relevant links:

* [Difference between bulleyes and bookworm CI results for applications](https://dash.yunohost.org/appci/compare/stable...bookworm)

- [x] Start an app testing campaign to identify regressions
- [x] Tweak dash.yunohost.org / Tartiflette to display this on a nice dashboard
- [ ] Fix regressions found in apps

**Comment by kay0u** [comment]
> Look for old legacy stuff in the core that can be dropped out

I can find:
- [ynh_legacy_permissions_exists and ynh_legacy_permissions_delete_all](https://github.com/YunoHost/yunohost/blob/4385c886a4375a813e8f7f4a646f0a4fdd00a013/helpers/permission#L353-L385), [some apps use these helpers](https://github.com/search?q=org%3AYunoHost-Apps+ynh_legacy_permissions_exists&type=code) but i think we can remove them and autopatch apps for bookworm migration
- [a fix from a regression in 3.5](https://github.com/YunoHost/yunohost/blob/4385c886a4375a813e8f7f4a646f0a4fdd00a013/src/backup.py#L2551-L2553), dunno what to do, we can probably remove it
- [Legacy stuff related to --log_type](https://github.com/YunoHost/yunohost/blob/4385c886a4375a813e8f7f4a646f0a4fdd00a013/src/service.py#L508-L512) dunno what to do
- [legacy stuff in services](https://github.com/YunoHost/yunohost/blob/bookworm/src/service.py#L660) looks important
- [something related to php 7.3 and buster->bullseye migration](https://github.com/YunoHost/yunohost/blob/4385c886a4375a813e8f7f4a646f0a4fdd00a013/src/service.py#L699-L702), we can keep it/adjust it for bullseye->bookworm migration?
- [avoid guid & uuid 1007](https://github.com/YunoHost/yunohost/blob/4385c886a4375a813e8f7f4a646f0a4fdd00a013/src/user.py#L220-L223) looks important too
- [and all the stuff in utils.legacy](https://github.com/YunoHost/yunohost/blob/bookworm/src/utils/legacy.py) which should be adapted for bookworm

**Comment by kay0u** [comment]
During the postinstall I get:
> Warning: ls: cannot access '/etc/php/*/fpm/pool.d/*.conf': No such file or directory
Warning: adduser: Warning: The home dir /var/vmail you specified can't be accessed: No such file or directory
Warning: grep: /run/resolvconf/resolv.conf: No such file or directory

Here the [full logs](https://paste.yunohost.org/raw/zarimoteno), but from what I understood:

- The first warning is because we're not installing php anymore, comes from [here](https://github.com/YunoHost/yunohost/blob/ea981ee4a614f89803684517fa2503b1787c1be2/hooks/conf_regen/01-yunohost#L189-L193)
- The second one looks like it comes from [dovecot regen conf](https://github.com/YunoHost/yunohost/blob/ea981ee4a614f89803684517fa2503b1787c1be2/hooks/conf_regen/25-dovecot#L44-L45C10), but I don't know why we don't have this folder anymore?
- And the last warning comes from [dnsmasq regen conf](https://github.com/YunoHost/yunohost/blob/ec6bf12a7479871831eb78380a4c28e8347d5577/hooks/conf_regen/43-dnsmasq#L70) 

-----------------------------------------------------------------------------------------------

After the postinstall, even though YunoHost-API was started, I couldn't access the webadmin (error 502), I had to restart it

Error from nginx:
> ==> /var/log/nginx/bookworm.tld-error.log <==
2023/09/11 09:22:25 [error] 3616#3616: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 10.34.87.1, server: bookworm.tld, request: "GET /yunohost/api/installed?locale=fr HTTP/2.0", upstream: "http://127.0.0.1:6787/installed?locale=fr", host: "bookworm.tld", referrer: "https://bookworm.tld/yunohost/admin/"

-----------------------------------------------------------------------------------------------

During nextcloud install, fail2ban took too much time to reload ([you can find some warnings](https://paste.yunohost.org/raw/ulivosajuc)). The issue here is the [`line_match` arg](https://github.com/YunoHost/yunohost/blob/465f6da5cd4d716bbcb802dfd742114083034235/helpers/fail2ban#L105) we should match `(Started|Reloaded) fail2ban.service - Fail2Ban Service` (there is a `fail2ban.service` to add)
There is also a warning in fail2ban service:
> fail2ban.configreader   [33783]: WARNING 'allowipv6' not defined in 'Definition'. Using default one: 'auto'

Moreover, I tried to get banned by entering the wrong password several times, but I didn't succeed.

That's all I've been able to see so far after installation

**Comment by Lab-8916100448256** [comment]
Things I have noticed while upgrading non YUNoHost systems from bullseye to bookworm that could have an impact on YUNoHost : 
- in default sshd_config, ChallengeResponseAuthentication has been deprecated and is now replaced by KbdInteractiveAuthentication. The old ChallengeResponseAuthentication option is still working but maybe we should swith to KbdInteractiveAuthentication?
- after the upgrade to bookworm I found that the ssh group has been renamed to _ssh, breaking ssh connection on systems that limit ssh access to the ssh group. To fix the situation I renamed the group back to ssh but maybe that was not the correct way to go. See https://www.reddit.com/r/debian/comments/148b4d5/new_name_for_ssh_group_in_debian_12/

**Comment by kay0u** [comment]
running postinstall on a fresh bookworm rebuild incus container:

postinstall fails because there is no dns resolvconf:
https://paste.yunohost.org/nukegaqoca.sql

```
root@ynh-dev-bookworm-unstable:/ynh-dev# cat /etc/resolv.conf 
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
# 127.0.0.53 is the systemd-resolved stub resolver.
# run "resolvectl status" to see details about the actual nameservers.

nameserver 127.0.0.1
root@ynh-dev-bookworm-unstable:/ynh-dev# resolvectl status
bash: resolvectl: command not found
root@ynh-dev-bookworm-unstable:/ynh-dev# systemctl status systemd-resolved
Unit systemd-resolved.service could not be found.
```

I think `systemd-resolved` should be installed, and I don't understand why it isn't.

Trying to fix it:
```
root@ynh-dev-bookworm-unstable:/ynh-dev# echo "nameserver 1.1.1.1" > /etc/resolv.conf 
root@ynh-dev-bookworm-unstable:/ynh-dev# apt update
Hit:1 http://forge.yunohost.org/debian bookworm InRelease
Hit:2 http://deb.debian.org/debian bookworm InRelease
Hit:3 http://deb.debian.org/debian bookworm-updates InRelease
Hit:4 http://deb.debian.org/debian-security bookworm-security InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
root@ynh-dev-bookworm-unstable:/ynh-dev# apt install systemd-resolved
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 yunohost : Conflicts: systemd-resolved but 252.22-1~deb12u1 is to be installed
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
```

Edit: no `systemd-resolved` shouldn't be installed. Then, I don't know what to do yet

**Comment by kay0u** [comment]
After the postinstall, I tried to connect to the webadmin, pressed the `Connect` button, nothing happens.
URL: https://ynh-dev-bookworm-unstable.incus/yunohost/admin/#/login?redirect=%2F

I changed URL to https://ynh-dev-bookworm-unstable.incus/yunohost/admin/, I'm logged in, works as expected.

My guess is there is `#/login?redirect=%2F` added at the end of the url which shouldn't be there, or we should redirect `#/login?redirect=%2F` to `#/` when use is logged in

**Comment by kay0u** [comment]
When I `CTRL + SHIFT + R` (refresh without cache), there is a `[GET] /domains` in the history, at the bottom of the webadmin (it's green, but it's always here, idk if it's normal)

**Comment by alexAubin** [comment]
Remaining major items : 
- [x] Fixing the major app regressions until we're left with a reasonable number like 10~5% / https://apps.yunohost.org/dash?filter=regressions_bookworm&hidedeprecated=true
- [x] Gotta reimplement DKIM signing with opendkim rather than rspamd (or bring rspamd back by default)
- [x] Clarify whatdo with the SSO basic HTTP auth header : with-password vs without-password
- [x] Replace metronome integration with a metronome app / https://github.com/YunoHost/issues/issues/2387
- [ ] Further test/stabilize the bullseye->bookworm migration procedure
    - [x] test on a server with many apps installed, identify weird UI/UX stuff
    - [ ] improve warning about unsupported apps .. maybe adding a new API to apps.yunohost.org to be able to list apps not compatible with bookworm
    - [x] Implement the Postgres migration (probably same as buster->bullseye but with 15 instead of 13 ?)
    - [x] Implement the python venv migration ? gotta re-study what are the python apps in the wild etc
    - [ ] Wat do with MongoDB
    - [ ] Test on RPi / Armbian :grimacing: 
- [ ] ???

**Comment by Salamandar** [comment]
I'd say the apps isn't a blocker anymore: 49 apps is less that 10%.

**Comment by kay0u** [comment]
Tested on my side with ~30 apps.

Works well, but I have to change the ssowat conf from `basic-without-password` to `basic-with-password` for some apps (roundcube and aeneria).

Moreover, I had to add `"protect_against_basic_auth_spoofing": false` to make nextcloud works on my PC and my phone.

And the python venv migration fails for all apps (which should be fixed by https://github.com/YunoHost/yunohost/pull/1912, but I can't test it after the migration), but a simple upgrade of the corresponding apps fixed the issue.

**Comment by Salamandar** [comment]
Same as kay0u. Tested with 42 apps. Here are the issues I had :
* baikal needs protect_against_basic_auth_spoofing=false
* python3.9-venv clusterfuck
* python migration broke
* tandoor could not upgrade
* yunohost-portal was not installed
* nginx was error 500 during migration (could not load .so…)
The rest worked perfectly.

**Comment by alexAubin** [comment]
Beta stage announcement: https://forum.yunohost.org/t/beta-stage-testing-for-yunohost-12-0-bookworm-and-bullseye-bookworm-migration/30496

**Comment by alexAubin** [comment]
Released as stable: https://forum.yunohost.org/t/31673
