### ISSUE TITLE
System hostname changes after installation

### ISSUE THREAD

**Issue by cruftex** [YunoHost/issues#2065]
After the installation the file `/etc/hostname` is set to the configured default domain name.
This seems to be a new behavior of YunoHost 11.

This is unexpected. I do have a different naming scheme for hosts and service domains. Also I rely on consistent hostnames for monitoring.

Is this needed?

**Comment by alexAubin** [comment]
This behavior is from the 2.x era at least ... Dunno why exactly, it's kinda practical for a bunch of things, the first one being that it's better to have `root@yourdomain` rather than `root@vps8547125495` in the shell with random names from your vps provider ... Anyway you can still change this manually after installing yunohost ...

**Comment by cruftex** [comment]
> Dunno why exactly...

Can you pls. keep it open so others can comment to this, too?

> Anyway you can still change this manually after installing yunohost

I have never seen any Unix installation running with the domain name as hostname.
It's good for YunoHost to stick to common practice. Although it might be practical and although
it might be the only Unix host one ever installs, it teaches a system setup that is different to any other.

Since this is default, scripts might also falsely assume that the hostname is always the domain name.

**Comment by alexAubin** [comment]
I don't know what to say : if this is not the common practice, then what is the common practice ? Naming the machine behind "foobar.domain.tld" `foobar` is something pretty common ... Many VPS around here have just a bunch of random numbers like `vps54849713`, how is that better than using the domain name ? What problem are you trying to solve exactly ?

**Comment by cruftex** [comment]
I don't know what to say, too :) There are two different names: the hostname, and the domainname. They are differently named, because these are different concepts.

If an admin wants the hostname to be the domainname that is totally okay. It might be okay in a situation when the machine is solely responsible for every operation that happens under this domain. Please mind that the fully qualified name of the machine is then `domain.domain.tld` and that the reverse lookup needs to be setup accordingly, otherwise mail sending will not work.

The setup tool sets the hostname identical to the domainname AND overrides previous choices of the adminstrator.

You said, I can change the hostname back, if I want. But I do not have any guarantee that a setup script assumes it to be identical to the domain name. Or is there are regular running test that tests every process with the hostname identical to the domain name and the hostname not identical to the domain name?

> Many VPS around here have just a bunch of random numbers like vps54849713, how is that better than using the domain name?

Exactly, that's why the first thing I do is to set a hostname.

**Comment by alexAubin** [comment]
Cheers I didnt realize the hostname and domain name were two different concepts ...

>The setup tool sets the hostname identical to the domainname AND overrides previous choices of the adminstrator.

Yes, just like YunoHost will override the SSH conf, the nginx conf, the root password, and many other things. The point of YunoHost is to setup all the technical aspects with sane default such that things can just work. The vast majority of people don't care about YunoHost changing the hostname. Hell, in a perfect world they shouldnt even have to open a terminal on the server ever. If  we start not configuring stuff because "0.1% of admins may not want to have <stuff> touched" then there's no YunoHost anymore.

>You said, I can change the hostname back, if I want. But I do not have any guarantee that a setup script assumes it to be identical to the domain name. Or is there are regular running test that tests every process with the hostname identical to the domain name and the hostname not identical to the domain name?

I dunno, I guess not, apart from the diagnosis which will warn you about reverse DNS being different from the main domain I suppose
