### ISSUE TITLE
USB flashed from 64bit PC iso is not bootable

### ISSUE THREAD

**Issue by andreatitolo** [YunoHost/issues#2080]
### Describe the bug

After successfully flashing the usb with the `.iso` file with Etcher, the USB is not bootable.

### Context

I tried with different USB sticks, different ports, using etcher on different operating systems and downloading the .iso different times to rule out corrupted downloads.

In the BIOS secure boot is disabled, if it matters.

Tried flashing other distros to see if it was a BIOS issue, but both ubuntu and kubuntu are bootable.

### To reproduce

   1. Go to https://yunohost.org/en/install/hardware:regular
   2. Download "Regular computer 64 bits - default" (https://build.yunohost.org/yunohost-bullseye-11.0.9-amd64-stable.iso)
   3. Flash the USB using Etcher -> Flash is completed successfully
   4. The usb is not recognized as a bootable device in the BIOS.

### Expected behavior

The usb should be recognized as a bootable device in the BIOS.

**Comment by Mollomm1** [comment]
i have the exact same problem with my hp laptop.

**Comment by narFnarF** [comment]
Similar issues:
https://github.com/YunoHost/issues/issues/2046
https://github.com/YunoHost/issues/issues/1340

**Comment by Deevad** [comment]
I was also affected by this today. 

`7018613d7ac47fc836f97c1192894a904896d22702ad382b20694526ae4fb42f  yunohost-bullseye-11.0.9-amd64-stable.iso`

Checksum matches, not a ISO corruption issue (I burnt it on various pendrive, with various image manager). And because I received a new mini PC server (an Asus PN41), I kept blaming the BIOS of this new hardware for not detecting the drive in the boot options. After 5h of trial and error, I had the idea to put a Ubuntu Server LTS iso on the pendrive and it worked. Same for a Debian 12 Bookworm net install iso. I wish I knew about this bug before. 😅 

Too bad for me. I was sort of hoping YunoHost could ease things for me. But I'll have to learn how to manually install everything from a Debian because YunoBoot. 🥲

**Comment by narFnarF** [comment]
@Deevad You can install Debian 11 (not 12!) and then install Yunohost on top of it. The YNH documentation on this topic is a bit vague, but I managed to make it work. I plan to write a guide soon.

**Comment by narFnarF** [comment]
Actually, @Deevad something that would be easier for you: Use Ventoy to create a usb-stick that can boot any iso file!
See the instructions I wrote here: https://forum.yunohost.org/t/installing-yunohost-on-an-old-intel-mac-pro-tower-computer-from-2008-2010/27970 (only look at the section about Ventoy)

**Comment by alexAubin** [comment]
(... I really need to dig into https://wiki.debian.org/RepackBootableISO to try to create new ISOs which work like the official Debian ISO does ... )

**Comment by alexAubin** [comment]
Alrighty 6 months later I finally had a look and was able to totally rework the way we build images. Instead of building them from scratch, they are now just "patched" / "repacked" version of the official Debian ISOs so it should *really* be more robust regarding firmware / bios / boot issues ... or I would be very much puzzled that the official Debian ISO works and the new YunoHost ones don't ...

The new ISOs are available on the usual install page (they shouldn't be worse than the old ones): https://yunohost.org/en/administer/install/images

There are also "testing" Bookworm images listed in https://build.yunohost.org/ for people willing to give this a try

**For both Bullseye and Bookworm, I am very much interested on feedback to test them on "real" machines to validate that they do boot properly after install, because I only tested those on virtualbox ...**

**Comment by alexAubin** [comment]
Some people reported that the new image did not work as expected on some setup (turn out EFI setups), ending up with Debian being installed but not YunoHost

This should be fixed with the new iteration

Closing assuming the original issue is fixed
