### ISSUE TITLE
[Proposition] YunoHost demo mode

### ISSUE THREAD

**Issue by yalh76** [YunoHost/issues#2081]
**how to enable it:**
`yunohost settings set demo_enable yes/no`
`yunohost settings set demo_user` ?
`yunohost settings set demo_password` ?
`yunohost settings set demo_webadmin_password` ?

**what should do the demo mode:**
- Default login on SSOWAT and on the webadmin : https://github.com/YunoHost/yunohost_demo/blob/7c8d36a2a8354f35bd210403b9224c8e47a7d650/upgrade.d/Constant_upgrade/Default_login#L10-L14
- Disable add domain : https://github.com/YunoHost/yunohost_demo/blob/1a04270c9db41375ef7c579a5c105b97363f0cfa/upgrade.d/Constant_upgrade/Disable_add_domain#L8-L9
- Display a message to say that the demo has come limitations
- Having an allow list of the apps and avoid this apps:
  - custom apps : https://github.com/YunoHost/yunohost_demo/blob/1a04270c9db41375ef7c579a5c105b97363f0cfa/upgrade.d/Constant_upgrade/Disable_custom_apps#L8-L9
  - wordpress
  - shellinabox
  - lufi
- Disable mail input/output and xmpp output, SSH at the guest 
- Maybe filter network at hypervisor level ? Only allow 80 and 443 out

**Comment by alexAubin** [comment]
Meh I don't remember what was the conclusion from the meeting the other day, I think we should rather keep all that logic in the demo's repository somehow, otherwise it feels risky that for some reason a bug (or people..) will enable the demo and transform a regular instance into Les Portes Ouvertes De YunoHost
