### ISSUE TITLE
Being able to list app setting keys

### ISSUE THREAD

**Issue by eauchat** [YunoHost/issues#2096]
I was wondering why there is not a way to list the setting keys an app proposes. Is it a design choice, or something somehow tricky to implement?

If it's easy enough to implement, I think it could be a great plus.
In the cli it could simply look like: `yunohost app setting <appId>`, not providing the setting key would just list the available keys.

It could be useful to explore what can be tweaked in an app, but also really precious when one doesn't remember the exact name of the setting they look for, it would spare having to open the app repository, look into the documentation or code to find out the setting key.

Just an idea ;)

**Comment by alexAubin** [comment]
>I was wondering why there is not a way to list the setting keys an app proposes [...] It could be useful to explore what can be tweaked in an app

Uuuuh yeah I think the reason is that we don't really want to encourage people to manually edit those ... I would rather be more tempted to *hide* the existing `setting set/get` commands (cf also https://github.com/YunoHost/issues/issues/2066) because too many people end up trying to manually tweak those (or even directly editing `settings.yml` or `conf/nginx.conf` or whatever), but *they don't do anything per se*. In fact you can probably break the app scripts by introducing inconsistencies between the settings and what's actually on the disk and what is in the setting ...

Not to mention that this key/value store also stores quite a bunch of purely technical key such as commit hashes, file hashes etc

The "real" stuff to tweak the app is the config panel, which you can somewhat use from the CLI, but is much more relevant from the webadmin

**Comment by eauchat** [comment]
Ok, got it.
For the info, I was thinking to borg_ynh which docs tells you to use the `yunohost app setting borg apps` to choose the apps to backup. But the doc is probably older than the existence of config panel.
(I guess the doc hasn't been updated because the idea may be to work more on integrating borg to core, which makes sense.)

Anyway, thanks for the explanation :)
And thanks for making me realize that borg now has a config panel :)

**Comment by alexAubin** [comment]
heuarg yeah indeed borg does this because it's a special case ;) It's really a system app developed specifically for YunoHost (similar to VPNclient and hotspot) and it does use the settings.yml as if it were its config file (because why not), but that's really not the case for regular webapps ;P
