### ISSUE TITLE
ynh_script_progression does not work in helper script

### ISSUE THREAD

**Issue by selfhoster1312** [YunoHost/issues#2122]
### Describe the bug

When using a `_common.sh` script for a package, using `ynh_script_progression` in the helper script produces the following warning:

```
/usr/share/yunohost/helpers.d/logging: ligne 308: $left_progression: expression de sous-chaîne négative
```

This behavior is not documented in function comments. And i did not see it in the web documentation, but maybe i missed.

NOTE: in this case _common.sh is sourced, not executed from install script.

**Comment by alexAubin** [comment]
would help to be able to read the actual code

**Comment by selfhoster1312** [comment]
You can find it [here](https://github.com/selfhoster1312/reverseproxy_ynh/blob/master/scripts/_common.sh#L40).

Placing the ynh_script_progression_lines in top-level scripts as i did before [this commit](https://github.com/selfhoster1312/reverseproxy_ynh/commit/bc55b0d0ff2150fcb379f3d79614bdaa68f269c8) produces no warning.

**Comment by alexAubin** [comment]
Hmyeah idk, it should work but this helper is clearly a dirty hack because to know how many steps are in the operation (install / remove / whatever), it `grep`s the calls to this helper in the current script (ie the `install` script for example). But this relies on heavy assumptions that no `ynh_script_progression` are gonna exist in external helpers, and that there's no advanced logic such as using this helper in a `for` loop

Anyway, I see that you got your inspiration maybe from the `redirect_ynh` app but it's really outdated I think ...

In particular, generating the nginx conf should only be a call to `ynh_add_nginx_conf`(ig?) and it will magically replace any `__FOOBAR__` string with the content of `$foobar` ... and copy the file to the right place, and reload nginx

Also more generally we tend to avoid factorizing the app scripts, even though as a developer it's tempting. It's difficult to summarize the entire discussion but basically this actually helps standardizing (and therefore collective maintenance) of the app scripts ... I mean this especially for `rp_make_permissions`, `rp_make_webconfig`, `rp_reload_web` ... `rp_validate_proxy_path` seems fine though since it seems to be purely validation that is quite specific to this app

The app packaging v2 format is coming in yunohost 11.1 and will help reducing some boring amount of repeated logic, though some part such as handling config files won't be handled through the new declarative format, we shall wait for the v3 format

**Comment by selfhoster1312** [comment]
I followed your recommendations in a later commit. Thanks.

I will try to make a new lint for this.

**Comment by selfhoster1312** [comment]
Closing because the lint got merged
