### ISSUE TITLE
Allow Certbot --nginx to function by altering ssowat.conf

### ISSUE THREAD

**Issue by veale** [YunoHost/issues#2135]
`/etc/nginx/conf.d/ssowat.conf` sets the parameter `server_names_hash_bucket_size 128`.

This means that certbot --nginx does not work, and afaik people cannot use it to get Let's Encrypt certificates for custom domains on their server. This is because (stupidly) the certbot system needs `server_names_hash_bucket_size 128` and only checks if it is in the `nginx.conf` file already. However, if I put it there, `nginx` won't start without me removing it in `ssowat.conf` because it is a duplicate directive. However, if I do *that*, then YunoHost stops updating `ssowat.conf` because it has been manually changed!

Certbot does not seem willing to alter its behaviour, and is sticking with the workaround that causes a problem see https://github.com/certbot/certbot/issues/5199

Is there a way for YunoHost to just require that `server_names_hash_bucket_size 128` be in `nginx.conf` instead and remove it from `ssowat.conf`?

**Comment by alexAubin** [comment]
But why do you want to use certbot in the first place ... YunoHost already support Lets Encrypt internally via acme_tiny ...

**Comment by veale** [comment]
Internally yes, and that works well for YunoHost services, but I also run services on my Let's Encrypt server that don't use Yunohost because the packages are not available or similar, or are unreliable, and would like them isolated from the domains that Yunohost manages the settings for. Of course I'd like to run these using Yunohost instead but I have not got the skills to package them up. One example is OnlyOffice, or Collabora for ARM, to integrate with NextCloud. I have tried using the reverse proxy yunohost app but it also ties in the new domains to the other YunoHost nginx settings which introduces errors and limitations. I am sure someone brighter than me could work out exactly what is able to be changed from Nginx files that Yunohost will then leave alone, but keep renewing, but I have not managed this.

**Comment by alexAubin** [comment]
Then I would encourage to report the limitations you found on the corresponding bugtracker (either this one or the corresponding app like `redirect_ynh` etc)

Closing as wontfix because we're definitely not gonna try to support the certbot use case, there are already too many things to work on and we can't spend dozens of hours on making workaround work instead of fixing the root issue..

Tweaking the `ssowat.conf` nginx snippet should be an acceptable solution for your edge case, it's not like we update this file super often ...
