### ISSUE TITLE
[manifest v2] data_dir not fully deprovisionned

### ISSUE THREAD

**Issue by fflorent** [YunoHost/issues#2161]
### Describe the bug

When I attempt an installation and a removal, the `$data_dir` seems not fully deleted.

I am not sure whether that's the expected behavior or a bug. If that's expected, can we guarantee that installing the application anew later would work (with the correct rights for the app)?

Note that I have not attempted a regular installation / removal of an application yet. I can try that upon request.

**Comment by alexAubin** [comment]
Yes this is the expected behavior, no we can't really guarantee that the new app will work and pick up the existing file, that's up to the packager to check this (I've seen some apps doing an `mv` if the data dir ain't empty)

We can't simply yolo-rm the data_dir as it may contain important, large data which are not backuped during the safety-backup-before-upgrade to save space

The data_dir may be removed when using the `--purge` option which should be made slowly more available from the webadmin
