### ISSUE TITLE
Manifest install questions : merge `pattern` and `filter`

### ISSUE THREAD

**Issue by Salamandar** [YunoHost/issues#2248]
### Describe the bug

According to the code, it looks like:

* BaseInputOption has a `pattern` option (regex + error reply) : https://github.com/YunoHost/yunohost/blob/5110cd0800faf8f406fe1bc69cb91199f2674a20/src/utils/form.py#L347
* AppOption has a `filter` option (javascript filter function ?) : https://github.com/YunoHost/yunohost/blob/5110cd0800faf8f406fe1bc69cb91199f2674a20/src/utils/form.py#L916

It looks like `filter` is not used anywhere. `Pattern` is used in some places (matrix bridge apps, to validate the synapse app).

In my understanding, it does the same thing : 
* `pattern` validates the value to validate the form
* `filter` "validates" the values to be available to the user (they can be expected to be valid afterwards)

### Suggested fix

A single common option, `pattern`, should do the trick. We could remove `filter` and use the pattern instead.
For now, `pattern` provides a `regexp` value. It could be someday extended to support the `filter` format (the js function) if really required.

(also `regexp` should be renamed to `regex`, and `error` could support translated strings :D )

**Comment by alexAubin** [comment]
filter was introduced to limit the available options in the case of the domain config panel in the core : 

```
./share/config_domain.toml-    [feature.app]
./share/config_domain.toml-        [feature.app.default_app]
./share/config_domain.toml-        type = "app"
./share/config_domain.toml:        filter = "is_webapp"
./share/config_domain.toml-        default = "_none"
```

the point is to limit the available choices only to webapps (because it doesnt make sense to define eg "borg" as the default app for a domain ..

My mind is not fresh on that topic to realize wether or not it could be merged with the `pattern` option .. naively the `pattern` is more about validating user input on the client side (eg a regex to check that it's an ipv4 before submitting the form) but maybe i'm confusing with the `pattern` attribute in html

**Comment by Salamandar** [comment]
Hmmm, alright, I did not have this knowledge.

Then `pattern` and `filter` could cohabit.

**Comment by Salamandar** [comment]
About the `pattern` option, it's used server-side in `_value_pre_validator`. My point is that it could *also* be used by the AppOption to pre-filter the list to help the user.

**Comment by Axolotle** [comment]
I would close this issue, `pattern` is indeed a validator (used both on client and core side with error handling), `filter` is used to filter choices on core side only before form declaration is sent to the client and is not a validator per se (no error handling).
