### ISSUE TITLE
Add option in admin web-interface to open LDAPS port for external applications

### ISSUE THREAD

**Issue by renne** [YunoHost/issues#2284]
Yunohost has a great LDAP integration for Yunohost apps.
There are external applications not available in Yunohost.

Editing `/etc/default/slapd` to open the LDAPS port conflicts with the checksum control system
in Yunohost and prevents updates of the file `/etc/default/slapd` by Yunohost.

Please add an option "Open LDAPS port for external applications" in `/yunohost/admin/#/tools/settings/misc`
to allow external applications to access LDAP data in a Yunohost compliant way including firewall rules, etc.

**Comment by alexAubin** [comment]
`Editing /etc/default/slapd to open the LDAPS port conflicts with the checksum control system
in Yunohost and prevents updates of the file /etc/default/slapd by Yunohost.`

It does not prevent editing the file, it just means that you manually edited configuration, and it's totally the expected behavior because exposing LDAPS for whatever purpose that you don't mention is an advanced use case.
