### ISSUE TITLE
option to completly disable https, across all apps and systems (IE, dont just just disable redirect, disable https entirly)

### ISSUE THREAD

**Issue by waikaeth** [YunoHost/issues#2319]
I dont need or want https, my yunohost services are only accessible via a wifi network at my house that does not connect to the internet. to install packages I use the backup / restore function in yunohost with a usb stick, which works nearly every time (to my amazment, fantastic job with that function btw). 

Its a homelab / private network, there is no need for https, im not worried about evil maids. 

But https causes huge headaches, because:

- Most android apps I've come across will accept either a working, signed https connection *OR* plain http, but *NOT* a self signed cert 
    - some examples off the top of my head are invoiceninja, firefly III apps, kimai2 apps, most matrix chat apps, many nextcloud apps like floccus
- Yunohost is *increadibly* aggressive at upgrading connections to https, often making it impossible to connect with plain http
- Therefore, **most android apps dont work with yunohost**

Even when I have supposedly disabled it with `yunohost settings set security.nginx.redirect_to_https -v False`, the default SSO login and any app that uses sso (and many do) often seems to want you to use https. Even apps that *dont* use the SSO login sometimes require a great deal of tinkering to work over plain http

Please give people like me who dont care about https an option to globally disable it. I hate having to dive into the configs for each and every single app just to wrangle with certs *again*, just so I can use the companion android app (which is very often the only reason I installed the software in the first place). Having to do so largely defeats the reason I use yunohost in the first place (lets you easily install neat webapps so you can quickly tinker with their UI to see how you like the ui / functionallity, rather then forcing you to tinker with the configs / settings / installation first)

**Comment by alexAubin** [comment]
>Yunohost is increadibly aggressive at upgrading connections to https, often making it impossible to connect with plain http

Yes sorry for trying to push basic security ... I don't even know what supposedly "agressive" stuff we do apart from the 301/302 redirection that can be disabled with the global setting

>I hate having to dive into the configs for each and every single app

And packagers will hate having to add "having to handle plain HTTP for the 3 person in the world interested by this" in addition to everything else they already have to care about

To me the issue is not about having plain HTTP, the issue is
- why insisting on having plain HTTP instead of using a normal domain name ... I mean even assuming you "care very much about your privacy and don't want stuff to transit over the internet" (in which case it's pretty ironic to want security while refusing HTTPS), you could have a normal domain name, connect your stuff to the actual internet once every 3 month, obtain a Lets Encrypt cert, map your domain name to 192.168.whatever on your local network, disconnect server from internet, and voila, no need to tinker everything
- apps should have a way to accept self-signed certificates - period. Self-signed certificate allow confidentiality without authenticity, which is a good thing as long as people don't yolo-accept stuff and get MITM. They are legit in some context. The issue is not "YunoHost insist on having HTTPS".

**Comment by alexAubin** [comment]
Closing due to lack of feedback, maybe user lost internet forever

**Comment by waikaeth** [comment]
> Closing due to lack of feedback, maybe user lost internet forever

Its great that you seem to have stable, consistent access to the internet. I dont. 

> Yes sorry for trying to push basic security ... I don't even know what supposedly "agressive" stuff we do apart from the 301/302 redirection that can be disabled with the global setting

In retrospect I should have foccused more on the fact that this "global setting" (assuming you are talking about `yunohost settings set security.nginx.redirect_to_https -v False`) is not a global setting at all in practice, and has not really worked [for over a year, for me at least](https://forum.yunohost.org/t/disable-https-redirect-because-many-apps-android-companions-that-wont-accept-self-signed-certs/20420). idk if its a bug or by design, but it does not work with the primary yunohost login screen (and thus by extension does not work with any app that relies on yunohost sso... i think, I've not extensivly tested tbh), and it also does not prevent apps from forcing their own https redirects. I'll open up a new issue bout it later. 

> apps should have a way to accept self-signed certificates - period

Well many of them dont. **period**. I've tried going back and forth with app devs about this issue, its very frustrating, and usually results in a very low priority issue or a "wontfix". I agree, apps should obviously have a way to accept self signed certs. but a whoooooole bunch of apps that I would very much like to use *dont*. 

> why insisting on having plain HTTP instead of using a normal domain name

I would not care at all about http vs https if it where not for the fact that a crap ton of android apps refuse to work with self signed certs.
