### ISSUE TITLE
Run tests without an actual Yunohost install

### ISSUE THREAD

**Issue by selfhoster1312** [YunoHost/issues#2386]
There are some tests in moulinette and yunohost modules but there is no documentation on how to run them. They are run in CI currently, but it would be nice to make sure we can run them before sending PR.

Even on a Yunohost install, it would be useful to document in README how to run the tests.

**Comment by alexAubin** [comment]
cf https://github.com/YunoHost/ynh-dev/blob/master/ynh-dev#L21, but to test `yunohost` you really do need a yunohost setup because you need a whole bunch of things, such as an LDAP database or nginx, etc ... It's pretty hard to imagine being able to mock everything

Moulinette tests can be ran more easily using `tox` iirc

**Comment by alexAubin** [comment]
Closing because `ynh-dev` addresses the issue ...
