### ISSUE TITLE
apt-clone : store complete installed .deb infos

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#241]
###### Original Redmine Issue: [240](https://dev.yunohost.org/issues/240)

Author Name: **julienmalik**

---

A VERY NICE tool I discovered : apt-clone (https://github.com/mvo5/apt-clone)
Packaged in debian (apt-get install apt-clone).

It is able to store information about the full list of installed .deb on an installation, in a way that it can be restored exactly later on a new system.

It is a much more powerful tool than the usual 'dpkg --get-selection' / 'dpkg --set-selection' way of doing :
- it stores information about the packages and track their availability in the remote repos.
- it is able to replicate a .deb that is not available in any source repo (not anymore, or because it never was since it was installed with dpkg -i) !!!

Run with :
sudo apt-clone clone --with-dpkg-repack /some/path/$(hostname)

and it will create  /some/path/$(hostname).apt-clone.tar.gz

I believe it would be a tremendous addition to core backup system.

**Comment by Psycojoker** [comment]
A little up because that looks pretty interesting cc @zamentur

**Comment by alexAubin** [comment]
That sounds very good for adminsys that know their stuff and everything, but since what we propose is to have transparent installations and backup/restore across different kind of architecture, I doubt this would be of any real interest in our case (except if we want to have an option `--backup-full-debs-but-you-will-need-to-restore-on-the-same-arch`) :/
