### ISSUE TITLE
[bookworm] WebUI buttons do not trigger the assigned function

### ISSUE THREAD

**Issue by BlindFish1003** [YunoHost/issues#2459]
### Context

- Hardware: *VPS*
- YunoHost version: 12.0.4.1
- I have access to my server: *SSH, WebUI, locally*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*

### Expected behavior

After migrating YH and Debian from bullseye to bookworm, some sections in the WebUI seem to be broken as the specific buttons do not trigger the expected action. E.g. actually i cannot perform system or app upgrades through the admin web interface. When the button is clicked, nothing happens, and the webpage sets itself into a state where no interaction is possible anymore until i reload the page. Updating however is still possible via CLI.

**Comment by Axolotle** [comment]
Hum, can't reproduce? Was it pre vue3?

**Comment by BlindFish1003** [comment]
Sorry, but actually i am not sure what you mean by vue3.

Currently, i am on 12.0.4.1 (testing), and the issue still exists.

**Comment by BilginSahin** [comment]
I have the same problem!

Hardware: VPS
YunoHost version: 12.0.6
I have access to my server: SSH, WebUI, locally
Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no

**Comment by nicofrand** [comment]
I can reproduce too in the upgrade section with the system upgrade button: the button triggers a modal  (to confirm the action) but the modal remains hidden due to `.fade:not(.show)`.

I do not know why the `.show` class is not applied though.

Browser's cache is emptied.
Browser: 133.0a1 (2024-10-24) (64-bit)

**Comment by nicofrand** [comment]
Seems to be exactly this issue: https://github.com/bootstrap-vue-next/bootstrap-vue-next/issues/2268 which is fixed in https://github.com/bootstrap-vue-next/bootstrap-vue-next/releases/tag/bootstrapvuenext-v0.25.2.

Version used is 0.24.x (https://github.com/YunoHost/yunohost-admin/blob/dev/app/package.json#L23).

**Comment by nicofrand** [comment]
Suggested solution from bootstrapvuenext: upgrade to v0.25.2+.

Workaround: do not disable animations on the OS side (ex. with KDE Plasma: do not set animation speed to "instant").

See https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion

**Comment by BlindFish1003** [comment]
Thanks for the information.

This update ist not done via apt command? Could you please let me know 
how to do it?

I am actually running on windows, and there is no such setting AFAIK.

**Comment by nicofrand** [comment]
It is literally described in the link I gave: https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion

**Comment by BlindFish1003** [comment]
Maybe it's due to accessibility issues, but i don't find any information 
about updating on this page.
