### ISSUE TITLE
ynh-dev: cannot resolve domains

### ISSUE THREAD

**Issue by fflorent** [YunoHost/issues#2463]
### Describe the bug

When I create a new incus container using ynh-dev, I cannot resolve any domain.

### To reproduce

Much like https://github.com/YunoHost/issues/issues/2145

``` bash
curl https://raw.githubusercontent.com/yunohost/ynh-dev/master/deploy.sh | bash
cd ynh-dev
./ynh-start
# now inside the incus container
dig perdu.com +short
# no answer from this command
```

### Expected behavior

The domain perdu.com is resolved out of the box.

### Workaround

It seems like `/run/dnsmasq/resolv.conf` is empty and that the reason why it does not work.

I run this command to add a nameserver and to make the name resolution work again:
```
echo "nameserver 1.1.1.1" > /run/dnsmasq/resolv.conf
```
(you may replace `1.1.1.1` by some other nameserver of your choice)

**Comment by x3rAx** [comment]
I experience the same issue.

However it's only on Debian Bookworm: `./ynh-dev start bullseye` can resolve hostnames without problems.

I noticed that in the `bullseye` image, `systemd-resolvd` is installed and active while `dnsmasq` has exited with an error because port `53` is already in use by `systemd-resolvd`. When I stop `resolvd` and restart `dnsmasq` it also fails to resolve.

With `./ynh-dev start bookworm` (or just `./ynh-dev start`) the `systemd-resolvd` service is not installed so `dnsmasq` a is able to start. However `systemctl status dnsmasq` reveals the following warning:

```
no servers found in /run/dnsmasq/resolv.conf, will retry
```

As @fflorent said, `echo "nameserver 1.1.1.1" > /run/dnsmasq/resolv.conf` allows `dnsmasq` to resolve hostnames again.

I think what ultimately needs to be done is to either find the gateway IP and add it as `nameserver` automatically or to add a setup step in the README to add a `nameserver` manually.

**Comment by alexAubin** [comment]
Yeah if I remember correctly it's kind of a chicken-and-egg problem because the dnsmasq resolver list is configured during postinstall, but the postinstall ain't done yet in the ynh-dev base image (on purpose)

I'm actually wondering how it works in real life for production servers (using the ISO image or ARM images)

**Comment by x3rAx** [comment]
Just tried it and the ISO tries to get IP configuration through DHCP during installation and if it fails it asks the user for IP/subnet, DNS and gateway. So the system would be initially configured having internet access.

I'm completely new to LXC/incus (only used Docker before) so I'm not sure about this but there seems to be some sort of DHCP inside the virtual network (`incusbr0`) that assigns the container an IP. I guess `dnsmasq` does for some reason not know about this.

**Comment by x3rAx** [comment]
I did some research and finally found that there seems to be no dhcp client running in the container. After running `dhclient` the name resolution works :ok_hand: don't know how it gets it's IP though but maybe that's just LXC magic :wink: 

So the fix might be to run `dhclient` after the container startup from within the `ynh-dev` script. I already opened a [PR](https://github.com/YunoHost/ynh-dev/pull/86) but this might not be the most elegant solution :man_shrugging: 

EDIT:
Wow that PR got merged really fast :smile:
