### ISSUE TITLE
Don't hardcode DynDns server in domain_add function 

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#253]
###### Original Redmine Issue: [253](https://dev.yunohost.org/issues/253)

Author Name: **opi**

---

While dyndns.py code is pretty generic (i.e. doesn't depend much on dyndns.yunohost.org server), the [`domain_add`](https://github.com/YunoHost/yunohost/blob/unstable/src/yunohost/domain.py#L94-L115) function have a much more dependent code.

- move the code that check for dyndns domain validity from domain.py to dyndns.py
- add an argument that allow to specify which DynDns server to use when calling `domain_add()` (like [`--subscribe-host`](https://github.com/YunoHost/yunohost/blob/unstable/src/yunohost/dyndns.py#L64).)

**Comment by alexAubin** [comment]
Closing because it's not like we are going to actually support different server considering there's only one known server running dynette ... What could make sense is to support different (existing) DynDNS providers but I doubt the API is the same as the dynette. "Refactoring dyndns.py to support multiple providers which have different API" is a totally different issue
