### ISSUE TITLE
SSO return a 500 error page after login

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#317]
###### Original Redmine Issue: [317](https://dev.yunohost.org/issues/317)

Author Name: **jerome**

---

This is due to this commit commit:ssowat|648b5522976854ea31b5c58cd1c995057e3b0cae:

```
2016/05/12 22:33:24 [error] 6009#0: *197 lua entry thread aborted: runtime error: /usr/share/ssowat/helpers.lua:307: attempt to index global 'ldap' (a nil value)
stack traceback:
coroutine 0:
        /usr/share/ssowat/helpers.lua: in function 'set_headers'
        /usr/share/ssowat/helpers.lua:474: in function 'get_data_for'
        /usr/share/ssowat/helpers.lua:427: in function </usr/share/ssowat/helpers.lua:376>, client: 109.190.172.57, server: example.org, request: "GET /yunohost/sso/ HTTP/1.1", host: "example.org"
```

**Comment by Psycojoker** [comment]
I think it's when ldap connection is lost. I've encountered similar errors.

**Comment by eauchat** [comment]
I have a similar issue trying to login as user, the page returns "500 Internal Server Error".
This occur in my case with one specific user.

I installed yunohost over debian, and there was a user on the debian machine, let's say it was called "jondoe". I wanted to create a user jondoe in yunohost, but yunohost wouldn't let me do it saying this user already exist on the machine. So I removed jondoe user with the command `userdel -r jondoe`. Then I added jondoe in yunohost and everything worked fine.  

Yes, but I'm not able to login with jondoe.  
I changed it's password at some point, then I decided to remove the user and recreate it.  
I noticed removing the user doesn't remove it's home and spool/mail directory, so I removed those manually before recreating the user. But same problem, impossible to login and "500 Internal Server Error".

Is there any way to make this user access yunohost?
Also is it safe to change users password or can it lead to this issue? Because this would be very problematic in case of someone completely not being able to access their account anymore after a password reset.

**Comment by alexAubin** [comment]
Hellow,

thanks for the feedback,

I think it's still unclear what happens exactly regarding this issue in general.

By any chance, does restarting nginx fixes the issue ? Otherwise, it'd be nice to have a look at nginx logs to debug the error 500. E.g. doing `tail -n 30 /var/log/nginx/the.domain.tld-error.log` right after getting the error.

>Also is it safe to change users password or can it lead to this issue?

I think that yes, changing user password might trigger this kind of issue, as discussed here or in other similar issues.

**Comment by alexAubin** [comment]
So does `systemctl restart nginx` fix the issue ?

**Comment by eauchat** [comment]
Oh sorry, yes I actually forgot this part of your suggestion.  
And, yes it solved the issue! :)
Is it also the way to go if this issue come up after a password change?

**Comment by alexAubin** [comment]
For now that's the workaround yes, but I guess the point is that SSOwat should "reinitialize" the ldap connection from time to time (or at the right time) when this happens ;)

**Comment by eauchat** [comment]
I just made a test, created a user, and see if I could log in with it, it worked.
Then I changed the password from the user interface and I could log in again with the new password, no problem.
Then I changed the password from the administration interface, and the error 500 came up.
So I ran `systemctl restart nginx` and I could login again.

**Comment by alexAubin** [comment]
Thanks :+1: That looks like a clear and easy way to reproduce the issue to be able to debug it :+1:

**Comment by alexAubin** [comment]
Should be fixed by https://github.com/YunoHost/SSOwat/pull/114
