### ISSUE TITLE
Translate documentation with Weblate tool

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#342]
###### Original Redmine Issue: [342](https://dev.yunohost.org/issues/342)

Author Name: **moul**

---

Translate documentation with [our Weblate tool](https://translate.yunohost.org).

I don't know which language we could take as source.

We sometime write first in french.

It depends what we want to do. Only french and english or more languages?

For many languages, english as source is the best.

I don't how Weblate is flexible to change language source for translation, and how does it handle large paragraphs.

It could also be used for announcements.

**Comment by Plumf** [comment]
Hello everyone, I have just come across this issue from 2016. Is it still relevant? I think that considering the number of translations that the documentation is beginning to require, this would be a practical tool. 

Is this technically possible actually ?

**Comment by alexAubin** [comment]
Hey there,

we recently discussed this with @e-lie who's pushing to migrate the current documentation to grav, which should be able to handle the whole i18n translation process more easily (not sure to remember exactly how...)

**Comment by Plumf** [comment]
If it's still under discussion, I don't know what makes the PeerTube documentation work, but it seems to me that the ambition is similar. But it can help : 
- https://docs.joinpeertube.org/#/
- https://framagit.org/framasoft/peertube/documentation

**Comment by visika** [comment]
Hi, I'd like to highlight a problem with the current translation system. I'm an Italian speaker and all the pages in my browser, like https://yunohost.org/#/install_on_raspberry or https://yunohost.org/#/isp show as _Nuova Pagina_ (New Page) because the website fetches the _it version by default; it would be sane to redirect to the English page if the translation is missing! I noticed this and found the English versions (so I can finally install YunoHost at home!) through some research, but another less tech-savvy Italian speaker would have been doomed.

**Comment by alexAubin** [comment]
Closing because it looks like we are not going to handle the doc translation using  weblate, it doesnt sound like a relevant tool for this

(Also moving to Grav fixed a bunch of issues related to funky behavior in simone mentioned in previous comment I think)
