### ISSUE TITLE
Wrong logfile link when post-install fails

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#768]
###### Original Redmine Issue: [768](https://dev.yunohost.org/issues/768)

Author Name: **nicofrand**

---

The post-installation failed and the following message appeared in the console:

> The following error was caught during YunoHost installation :
> 
> Post-installation failed
> 
> 
> Installation logs are located in /var/log/yunohost-installation.log

However the correct log now seems to be /var/log/yuonohost/yunohost-cli.log.

**Comment by alexAubin** [comment]
It's actually because /var/log/yunohost-installation.log is the install_script's log which launches the postinstall, then the "real" log becomes yunohost-cli.log ... Personally I stated in another issues I would just remove the postinstall thing from the whole install_script since that makes things overly complicated/weird for several different complicated reasons :/

**Comment by alexAubin** [comment]
Indirectly fixed via https://github.com/YunoHost/install_script/pull/54
