### ISSUE TITLE
Allow aliases when creating a domain

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#796]
###### Original Redmine Issue: [796](https://dev.yunohost.org/issues/796)

Author Name: **nicofrand**

---

I own a blog which is hosted at the root of my domain, *domain.tld*.
I'd like it to be accessible from *www.domain.tld* and *blog.domain.tld* too, without redirections.

It would be great if I could specify aliases when creating the domain in YunoHost.
That would specify the `alias` directive in nginx but also, it would tell Let's Encrypt (or the self-signed cert) to validate the 3 domains.

**Comment by alexAubin** [comment]
I really doubt that domain aliases can actually be implemented technically ... In practice, many apps in the way they are developed are tight coupled to one specific domain and that's it.

For instance, in wordpress, a "permalink" to a blog contains the domain of the blog, and I don't see how you could tell wordpress that a single blog should be accessible from multiple location transparently... (as in "rewrite all the page with domain foo.tld instead of bar.tld)

**Comment by ashledombos** [comment]
Well it's generally used for serving static files (images, JS ...) without cookie. It's easily doable with a reverse proxy, but it should not be displayed as an app to users.
