### ISSUE TITLE
Allow to use TLS only / disable HTTP when creating a domain

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#803]
###### Original Redmine Issue: [803](https://dev.yunohost.org/issues/803)

Author Name: **nicofrand**

---

When creating a new domain, I'd like to be able to either disable the port 80 on this domain or to redirect it to the port 443 (with HSTS).
I'd like to do it from both CLI and web interface.

**Comment by alexAubin** [comment]
Closing because meh, that's gonna create more trouble than security, people are gonna disable HTTP thinking it's gonna make things "more secure" when in fact that's going to prevent Lets Encrypt cert install and people are going to be confused why they get an error typing "foobar.tld" in their browser because browsers are stupid and test http by default.

Also you can pretty much get this by disabling port 80 in the firewall
