### ISSUE TITLE
dyndns cron spam mail because of time out

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#807]
###### Original Redmine Issue: [807](https://dev.yunohost.org/issues/807)

Author Name: **alexAubin**

---

Many user have reported ~recently that they receive a lot of email from the dyndns cron due to timeout (or other issues). Even if the IP didn't changed.

>Communication with server failed: timed out. Unable to update IP address on DynDNS.

Maybe we could optimize the dyndns cron to attempt to update only if the IP changed (or is different from what is resolved by an external DNS)

We could also have an error counter and send an email only if it failed like, say, the last 3 times.

**Comment by Aaaamu** [comment]
Hi,
since a few days, I have troubles with moulinette / dyndns. I get Mails every 2 Minutes and the dns server seems unreachable
Mail:
Cron <root@em> yunohost dyndns update >> /dev/null

Traceback (most recent call last):
  File "/usr/bin/yunohost", line 72, in <module>
    parser=parser
  File "/usr/lib/moulinette/yunohost/__init__.py", line 29, in cli
    top_parser=parser
  File "/usr/lib/python2.7/dist-packages/moulinette/__init__.py", line 120, in cli
    args, output_as=output_as, timeout=timeout
  File "/usr/lib/python2.7/dist-packages/moulinette/interfaces/cli.py", line 477, in run
    ret = self.actionsmap.process(args, timeout=timeout)
  File "/usr/lib/python2.7/dist-packages/moulinette/actionsmap.py", line 592, in process
    return func(**arguments)
  File "/usr/lib/moulinette/yunohost/log.py", line 358, in func_wrapper
    result = func(*args, **kwargs)
  File "/usr/lib/moulinette/yunohost/dyndns.py", line 219, in dyndns_update
    old_ipv4 = check_output("dig @%s +short %s" % (dyn_host, domain)) or None
  File "/usr/lib/python2.7/dist-packages/moulinette/utils/process.py", line 31, in check_output
    return subprocess.check_output(args, stderr=stderr, shell=shell, **kwargs).strip()
  File "/usr/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command 'dig @dyndns.yunohost.org +short em.nohost.me' returned non-zero exit status 9
#############################################################
seems to be the same problem again? my dns was autoconfigured on yunohost installation, my domain is em.nohost.me

**Comment by Psycojoker** [comment]
Hello @Aaaamu,

Thx for reporting, we have pushed a fix for that here https://github.com/YunoHost/yunohost/pull/1140 and this is related to the current DDoS on our infra https://forum.yunohost.org/t/infrastructure-is-currently-under-ddos-you-may-experience-issues-with-various-services/13981

Sorry for the troubles, it should be fixed at some point,

**Comment by Aaaamu** [comment]
Thanks for the super fast response!!! - can one help in some (lay) way
in fighting the attack?

Am 18.01.21 um 20:44 schrieb Bram:

**Comment by tiotrom** [comment]
I get this:
```
Failed to resolve dyndns.yunohost.org
```
Even tho we do not have a dynamic IP. And I get an email about the above error daily...do I need to do anything or just ignore it?
