### ISSUE TITLE
dyndns wants to update way too often

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#843]
###### Original Redmine Issue: [843](https://dev.yunohost.org/issues/843)

Author Name: **alexAubin**

---

Right now, the cron job for dyndns update runs every 2 minutes (!!!) 

https://github.com/YunoHost/yunohost/blob/aad37409333895051e505c944b2ec05790d2fb46/src/yunohost/dyndns.py#L266

Apriori this is not too bad since dyndns_update checks if the IP changed... but to check what's our IP, there's a request to ip.yunohost.org. 

Result : https://framapic.org/vKn8987Pmskx/LTE8IkrVww9o.png

**Comment by Psycojoker** [comment]
@alexAubin still relevant? 

Since ip.yunohost.org is done in full nginx config it can handle a very very high load.

**Comment by alexAubin** [comment]
Indeed we might be able to handle the load now :wink:
Though imho it's more a general question of : 
- this is really brutal design and we could do better ? I mean do we really need to check this every 2 minutes and not, for instance, every 10 ? What are the constrains behind that / what are we trying to achieve
- centralization : when our infra goes down, every instance with nohost.me/noho.st panicks and flood email to its root because it cant contact ip.yunohost.org :s 
- maybe there are some privacy concerns to have with the fact that we receive a ping of those instance every 2 minutes (surely that's not the same scale of sending all your pics to facebook, but still a bit odd)

**Comment by Psycojoker** [comment]
Hard problem :confused: 

* tbh I'm not really chocked about the 2min, it improves the UX (less downtime, 2min is fine vs 10min "something is broken") and it's not that costly is it?
* I guess we can try to find a shitload of other places where to put a ip.* (since it's only a nginx config file it's super easy to deploy) and randomly select in it until we get one working
* but that won't solve the privacy issue because we'll eventually get the ip because on how often this information is asked and worst this information will be spread on several servers :(

**Comment by alexAubin** [comment]
>tbh I'm not really chocked about the 2min, it improves the UX (less downtime, 2min is fine vs 10min "something is broken") and it's not that costly is it?

It improves the UX for the (imho) marginal case where the user IP really is dynamic and does changes really often. For the rest of the people : 
- they get scared by the flood of screaming emails when we have downtime on our infrastructure, c.f. https://forum.yunohost.org/t/errno62-cron-yunohost-dyndns-update-dev-null/4539/8 for example
- every now and then, `dig` is not able to fetch the record from dyndns.yunohost.org for some reason (not too surprised that 0.1% of the time the server doesn't answer fast enough or idk) which ends up producing something like 2~5 emails *per day* complaiming about `subprocess.CalledProcessError: Command 'dig @dyndns.yunohost.org +short domain.ynh.fr' returned non-zero exit status 9` with a huge stacktrace. Then people come asking about it on the forum pretty regularly. I suppose we could add a mechanism to retry the dig a few times if it failed...

**Comment by icf20** [comment]
imo this should have a option to disable in case of a setup on firewall/diode where all outgoing traffic is blocked so it wont produce a email every 2 minutes

(had this on testing vm and i forgot to check the email and i went to 35 000 emails)

**Comment by alexAubin** [comment]
To be finally addressed by https://github.com/YunoHost/yunohost/pull/1149 ...
