### ISSUE TITLE
Debian's package changelogs are never displayed in web-admin

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#897]
###### Original Redmine Issue: [897](https://dev.yunohost.org/issues/897)

Author Name: **jibec**

---

hi,

when we get packages updates from web administration, the contextual information isn't correct as it talks about Ubuntu.

libjasper1 libjasper1:amd64

La liste des modifications n'est pas encore disponible.

Veuillez utiliser http://launchpad.net/ubuntu/+source/jasper/1.900.1-debian1-2.4+deb8u3/+changelog
jusqu'à ce que les changements soient disponibles ou essayer plus tard.

Is this the kind of content we would like to get? http://metadata.ftp-master.debian.org/changelogs/main/j/jasper/stable_changelog

thanks for your help

**Comment by alexAubin** [comment]
Closing / wontfix, because debian changelogs are super technical and boring as hell, un-understandable by non-tech users, and usually they don't contain anything useful - upgrades just work. 

However, we should encourage people to checkout Yunohost's release note as sometime they contain important details. c.f. https://github.com/YunoHost/issues/issues/1214
